### ISSUE TITLE
在使用诸如V2ray，shadowsocks等代理软件时应如何进行配制？

### ISSUE THREAD

**Issue by hendrixone** [derekhe/msfs2020-google-map#1]
如题，自己试了一通并没有成功，希望作者能给予点帮助

**Comment by derekhe** [comment]
这些软件都会给你生成一个http的代理地址，你检查一下这些软件的界面，有没有http://127.0.0.1:xxxx之类的

**Comment by derekhe** [comment]
请试试最新的1.1.0版本，有朋友已经测试成功

**Comment by hendrixone** [comment]
搞定了，高空好看多了，大佬厉害
