### ISSUE TITLE
无法显示3D楼房

### ISSUE THREAD

**Issue by faker320** [derekhe/msfs2020-google-map#10]
如图
![image](https://user-images.githubusercontent.com/85487730/130272037-5c71f643-3076-43e4-a92f-1e496833fc2f.png)

**Comment by derekhe** [comment]
这个原理是替换bing地图的地皮到google，立体的东西没有替换也没办法替换。

**Comment by faker320** [comment]
可是游戏里的立体东西不是依据卫星图ai生成的么

------------------ 原始邮件 ------------------
发件人: hesicong ***@***.***&gt;
发送时间: 2021年8月21日 12:19
收件人: derekhe/msfs2020-google-map ***@***.***&gt;
抄送: faker320 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[derekhe/msfs2020-google-map] 无法显示3D楼房 (#10)

**Comment by derekhe** [comment]
AI是在服务器上，不是本地的游戏中

**Comment by derekhe** [comment]
我已经在说明中更新，关贴了哈
