### ISSUE TITLE
[BUG] exception faults

### ISSUE THREAD

**Issue by Seb-a320** [derekhe/msfs2020-google-map#103]
**Describe the bug**
A lot of exception errors.

**To Reproduce**
Each start

**Screenshots**
![cmd_06uiXZNLH0](https://user-images.githubusercontent.com/85013247/142723460-57f00a5f-2aab-4bdd-983d-b81487b6bdeb.png)

**Desktop (please complete the following information):**
 - OS: w11
 - MOD Version 2.3.0
 - MSFS Version : last one

**Comment by derekhe** [comment]
This may because access to google server is slow, please try to switch another google server.
