### ISSUE TITLE
443 port issue

### ISSUE THREAD

**Issue by xXJ4mesXx** [derekhe/msfs2020-google-map#104]
Hi, when i tried to open the file "run.bat" gave me this error "You have application using 443 port, please close them, application will close."
What can i do to fix this, i think i don't have applications running in this port.
![imagem_2021-11-20_123734](https://user-images.githubusercontent.com/29248429/142726535-fe5eafe8-e53b-4109-8321-4a975ede8cf2.png)

**Comment by derekhe** [comment]
Always use latest version
Try: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#443-port-is-occupied

**Comment by xXJ4mesXx** [comment]
THANK YOU! It's fixed.
