### ISSUE TITLE
Since msfs 2020 Vers. 1.21.13 no 3-D buildings in contrast to before 

### ISSUE THREAD

**Issue by erdmaennchen53** [derekhe/msfs2020-google-map#106]
Hi He Sicong,
thank you so much for this tool. it's great! It brings a lot of fun in the simulator, especially if you fly an helicopter. But since the new msfs 2020 version 1.21.13 I have problems with 3-D buildings in my hometown Karlsruhe in Germany. Before all buildings were in 3-D and all buildings were original. but now I only have flat images and several bad 3-D buildings. I've read and followed all of your instructions. Do you use other maps? Thanks for all!

BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
Please give me some screenshots and location (lat and lon)

**Comment by erdmaennchen53** [comment]
![Karlsruhe1](https://user-images.githubusercontent.com/73026970/142732301-af7901d0-41bc-4be9-bb61-1d1d80cd220e.PNG)
![Screenshot 2021-11-20 162723](https://user-images.githubusercontent.com/73026970/142732312-ff302c7c-0781-4e55-a8ed-641f003bfdf6.png)
![Screenshot 2021-11-20 162831](https://user-images.githubusercontent.com/73026970/142732319-99567705-95ae-432e-b883-69a913dd1f64.png)
![Screenshot 2021-11-20 162909](https://user-images.githubusercontent.com/73026970/142732327-0a519937-d2b5-4645-b14f-f002671a827c.png)
![Screenshot 2021-11-20 163631](https://user-images.githubusercontent.com/73026970/142732330-4c30b9ee-493e-413e-9cbf-4032caffb97c.png)
The last screenshot is with lat and lon.

**Comment by Marakai** [comment]
I've had similar issues and watching the logs noticed that queries will time-out and fail massively after first starting OK. Could it already be that Google Maps is throttling queries?

**Comment by erdmaennchen53** [comment]
Hallo,
thank's for your answers. I don't know what the problem is. If I watched the datatransfer in the windows powershell it runs very quickly without stopping. I made onemore some screenshots. one of them is the railwaystation in Karlsruhe directly out of google maps (3-D). The same position out of MSFS 2020 with flat images. I have no idea. Thank you and have a nice day

![Screenshot 2021-11-21 135212](https://user-images.githubusercontent.com/73026970/142763898-c772a6db-8d61-489b-b4b9-223ff69f9b0b.png)

![Screenshot 2021-11-21 143011](https://user-images.githubusercontent.com/73026970/142763914-68be0767-6322-404f-8493-b22434eac956.png)
![Screenshot 2021-11-21 134555](https://user-images.githubusercontent.com/73026970/142763928-f9883aec-246f-4bf1-b8e7-169b33860302.png)
![Screenshot 2021-11-21 141440](https://user-images.githubusercontent.com/73026970/142763948-425867ea-e163-4107-8ad1-c8e727f38900.png)

**Comment by erdmaennchen53** [comment]
![Screenshot 2021-11-21 141604](https://user-images.githubusercontent.com/73026970/142764070-f0abbc30-ee77-4ac6-bda7-c93612a2d29c.png)

**Comment by derekhe** [comment]
I think the images are loading correctly. You can compare bing with with Google, there shouldn't be any different regarding buildings which are pre-built by microsoft. So if somewhere in Google shows the building, but you can't find the 3D building (also can't in bing), it is correct.

**Comment by derekhe** [comment]
@erdmaennchen53 does my answer make sense to you?
