### ISSUE TITLE
Windows command prompt opens for a few seconds then disappears

### ISSUE THREAD

**Issue by gazzover67** [derekhe/msfs2020-google-map#11]
How to solve this problem? Installed Python 3.9 from windows store. Removed url line in config.ini & add 2 lines in hosts file.

**Comment by derekhe** [comment]
Please try use the release version here: https://github.com/derekhe/msfs2020-google-map/releases/download/1.3.0/msfs2020-google-map-2021-08-20.zip
unzip it and edit config.ini
then run: server.exe with administrator right
make sure there is no antivirus warning (better to disable it for a while)
if any certificate error, just click "yes"

**Comment by gazzover67** [comment]
i used this version and ran as administrator

**Comment by gazzover67** [comment]
I made a screen recording to catch a message frame from the command line and this is the error it showed:
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by derekhe** [comment]
Maybe you have some service running on 443 port? Please find and kill them.

**Comment by gazzover67** [comment]
Yeah:) Thanks, i find this service. This is vmware-hostd.exe
