### ISSUE TITLE
[BUG] NGINX License missing

### ISSUE THREAD

**Issue by Marakai** [derekhe/msfs2020-google-map#110]
**Describe the bug**
Nginx is included in the repository in binary form without the required license.

As per the NGINX license in https://github.com/nginx/nginx/blob/master/docs/text/LICENSE 👍🏼 

```
2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
```

**Solution**
Add `LICENSE` from NGINX to repo.

**Comment by derekhe** [comment]
Thanks, already added in latest commit.
