### ISSUE TITLE
Stuck at 75% after Clicking "FLY" in Map Menu

### ISSUE THREAD

**Issue by emt3072** [derekhe/msfs2020-google-map#111]
Loading screen stuck at 75% after clicking "FLY" in the map menu.
Spent all day trying to figure it our and narrowed it to this app. Last night I was able to start MSFS2020 google map while MSFS was frozen and it loaded but the maps looked offline. Still have no been able to load for tha last 3 hours. Just installed the latest version, cleared the cache to no avail. MSFS is installed on an external drive.  Everything seemed to work until about 2 days after update 7

Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM	32.0 GB (29.9 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by derekhe** [comment]
Someone meet the same issue as fix is, could you have a look?
![image](https://user-images.githubusercontent.com/1734077/143011715-73d3ba21-c2a7-463f-84f7-1b8f360980d9.png)

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2

**Comment by derekhe** [comment]
@emt3072 fixed?

**Comment by emt3072** [comment]
Yes thank you!
