### ISSUE TITLE
Usability improvements with better packaging and auto-run 

### ISSUE THREAD

**Issue by ajs117** [derekhe/msfs2020-google-map#112]
Package the solution as an .exe using pyinstaller. Then similar to FSRealistic or FS2CREW auto-launch on sim launch and auto-close on sim close. Integrate log console in main window.

**Comment by derekhe** [comment]
I'm planning to use electron to improve this and rewrite the whole thing using js, then these problems should gone.
My first version is created by Pyinstaller but the problem is the application created by Pyinstaller will be detected as virus. This prevent a lot of thing.
