### ISSUE TITLE
[BUG] Crash causes FS2020 to loose it's cert with MS.

### ISSUE THREAD

**Issue by johnflyersmith** [derekhe/msfs2020-google-map#115]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
If this crashes you will not be able to re-install FS2020. Your purchase will not show in the MS store or Xbox app.

**To Reproduce**
I guess you could loose power like I did.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MOD Version msfs2020-google-map-2021-11-20_KNvzM
 - MSFS Version, MS Store

**Comment by derekhe** [comment]
Please restart the mod again and click the "stop" button, it will restore all things.

**Comment by derekhe** [comment]
@johnflyersmith fixed?
