### ISSUE TITLE
Mod crashed in game and now Bing maps not loading.

### ISSUE THREAD

**Issue by rexetorize** [derekhe/msfs2020-google-map#116]
**Describe the bug**
I was using the mod and it crashed but the game was on. When I restart the game it is loosing it's online connectivity. Bing maps not loading. 

**To Reproduce**
Close without pressing the stop button in the mod.

**Desktop (please complete the following information):**
 - OS: windows 10
 - MOD Version latest
 - MSFS sim update latest ,  Steam

**Comment by derekhe** [comment]
Please start the mod again and press stop button, it should be good.

**Comment by rexetorize** [comment]
I did try that but didn't work, so I'm reinstalling.

**Comment by rexetorize** [comment]
Any other suggestions?

**Comment by derekhe** [comment]
Please have a look at these FAQ (https://github.com/derekhe/msfs2020-google-map/wiki/FAQ) , try to restore your hosts file

**Comment by Nolema** [comment]
> Any other suggestions?

This mod can change your HOST file,you can try to reset it

**Comment by derekhe** [comment]
@rexetorize if no response for another 2 days, I will close this.

**Comment by rexetorize** [comment]
oh yeah changing the host file worked, thanks/
