### ISSUE TITLE
运行离线缓存时，运行内存占用极大

### ISSUE THREAD

**Issue by Rikkalxn** [derekhe/msfs2020-google-map#12]
![image](https://user-images.githubusercontent.com/84234793/130325703-90bed21d-3f9d-4659-b7dc-a88b4ba30ef2.png)
请问为什么在运行离线缓存时，内存占用极大？

**Comment by derekhe** [comment]
我这里看起来一切正常，请问是运行一段时间后这样的么？
![image](https://user-images.githubusercontent.com/1734077/130325853-00fd6eb4-60e1-4812-8474-c33a8136dc72.png)

**Comment by Rikkalxn** [comment]
它就是运行内存一直在递增，没有出现下面的三个分支，会不会是因为设置的精度范围过大过高导致的呢？

**Comment by derekhe** [comment]
我空了看一下，他是会存到磁盘里面的，但不知道为啥占用那么多内存。

**Comment by Rikkalxn** [comment]
好的，谢谢大佬了
