### ISSUE TITLE
[BUG] ERROR: Could not find a version that satisfies the requirement Flask==2.0.1

### ISSUE THREAD

**Issue by Stevenlau0426** [derekhe/msfs2020-google-map#122]
**Describe the bug**
The error messages appeared when I start the program

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the run.bat file as administrator
2. Error messages appeared in the cmd

**Screenshots**
![Screenshot 2021-11-27 220704](https://user-images.githubusercontent.com/95134454/143684982-46f05f81-7e99-454b-b244-031729288e67.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - MOD Version 2.3.1 (posted on 2021-11-24)
 - MSFS Version: Stream

**Additional context**
I tried turning off the anti-virus software to run the program, but the same error messages still showed up in the cmd.

Thank You.

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2

**Comment by Stevenlau0426** [comment]
The previous error messages are now gone, and the control panel of the program can be successfully loaded up but now a new error message is showing in the cmd. 
![Screenshot 2021-11-28 183611](https://user-images.githubusercontent.com/95134454/143764457-8e383803-be44-40df-8a7b-96c9db178eee.jpg)

**Comment by derekhe** [comment]
Have a look at: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-related-issue

**Comment by Stevenlau0426** [comment]
The mod works like a champ now! Thank You!
