### ISSUE TITLE
cannot find hosts file

### ISSUE THREAD

**Issue by tonygoole** [derekhe/msfs2020-google-map#128]
hi im getting this error message

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Windows\\System32\\drivers\\etc\\hosts

in guessing it is because my windows is installed on H drive and not C.

is there any way to resolve this ?

**Comment by cuteskater** [comment]
try to rename it? to h:

**Comment by tonygoole** [comment]
i tried it would not let me

**Comment by cuteskater** [comment]
why? try it with admin right?

**Comment by tonygoole** [comment]
It just said invalid parameter

**Comment by cuteskater** [comment]
you can rename the drive h: to c: i think

**Comment by derekhe** [comment]
you can try find out the runner.py and change this line: host_path = "C:\\Windows\\System32\\drivers\\etc\\hosts"
into H:\\

**Comment by Xpress690** [comment]
mine has all the right drive letter correct but still not working and showing the
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Windows\System32\drivers\etc\hosts
thank you

**Comment by derekhe** [comment]
@Xpress690  please have a look: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-not-found

**Comment by derekhe** [comment]
Can you find this file?

**Comment by Xpress690** [comment]
> Can you find this file?

Yes I can..... I´ve done everything that you asked me to do, and stilb is not working.

thank you

**Comment by Xpress690** [comment]
This is my problem:
![Google](https://user-images.githubusercontent.com/54308597/144843081-715ae215-1b02-49d1-a178-3d359dad7947.PNG)
