### ISSUE TITLE
Use another map replace the google map?

### ISSUE THREAD

**Issue by h0wardch3ng** [derekhe/msfs2020-google-map#13]
Mapbox satellite data is newest

**Comment by Artoria2e5** [comment]
The [`cntms`](https://github.com/gumblex/cntms) library will also be useful for providing not-quite-satellite imagery. For all the servers providing ESPG:3857 (Web Mercator) tiles, all you need is to change the single line at https://github.com/derekhe/msfs2020-google-map/blob/f244a00b06657090fbaff6f3362bf2a0527629c3/offline-cache.py#L35.

**Comment by derekhe** [comment]
It should be ok. If you have credentials for mapbox, please change the code as your need.

**Comment by h0wardch3ng** [comment]
@derekhe @Artoria2e5 

Mapbox Tile URL Templates

`https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?sku={yourSKUToken}&access_token={yourToken}`

SKU Token and Access Token can apply mapbox free plan, 200,000 free tile requests per day.

------

This tool might be a GUI program(Use `PyQt` or `PyInstaller` package code to .exe file, to avoid user install python environment), and able to configure tile URL templates just like QGIS

### Satellite Map Tile URL Templates

Google Map Satellite

https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z} 

Google Map Hybrid

https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z} 

Bing Map Satellite
http://ecn.t3.tiles.virtualearth.net/tiles/a{q}.jpeg?g=1 

-----

### Non-Satellite Map Tile URL Templates

Google Map
https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z} 

OpenTopoMap

https://tile.opentopomap.org/{z}/{x}/{y}.png 

OpenStreetMap

http://tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by derekhe** [comment]
For China, google map is best :)
I have use PyInstaller to create a exe file, but it reports virus when I update load to flightsim website. So I only give source code for that user. I recommended to use the exe file I made in release page.

**Comment by h0wardch3ng** [comment]
I find a way to access Google Map satellite tile picture, avoid use local proxy.

Use Cloudflare Works service as reverse proxy

------
# 1. Add new worker script

```
const config = {
  basic: {
    upstream: 'https://mt3.google.com',
    mobileRedirect: 'https://mt3.google.com',
  },

  firewall: {
    blockedRegion: [],
    blockedIPAddress: [],
    scrapeShield: true,
  },

  routes: {
  },

  optimization: {
    cacheEverything: false,
    cacheTtl: 5,
    mirage: true,
    polish: 'off',
    minify: {
      javascript: true,
      css: true,
      html: true,
    },
  },
};

async function isMobile(userAgent) {
  const agents = ['Android', 'iPhone', 'SymbianOS', 'Windows Phone', 'iPad', 'iPod'];
  return agents.any((agent) => userAgent.indexOf(agent) > 0);
}

async function fetchAndApply(request) {
  const region = request.headers.get('cf-ipcountry') || '';
  const ipAddress = request.headers.get('cf-connecting-ip') || '';
  const userAgent = request.headers.get('user-agent') || '';

  if (region !== '' && config.firewall.blockedRegion.includes(region.toUpperCase())) {
    return new Response(
      'Access denied: booster.js is not available in your region.',
      {
        status: 403,
      },
    );
  } if (ipAddress !== '' && config.firewall.blockedIPAddress.includes(ipAddress)) {
    return new Response(
      'Access denied: Your IP address is blocked by booster.js.',
      {
        status: 403,
      },
    );
  }

  const requestURL = new URL(request.url);
  let upstreamURL = null;

  if (userAgent && isMobile(userAgent) === true) {
    upstreamURL = new URL(config.basic.mobileRedirect);
  } else if (region && region.toUpperCase() in config.routes) {
    upstreamURL = new URL(config.routes[region.toUpperCase()]);
  } else {
    upstreamURL = new URL(config.basic.upstream);
  }

  requestURL.protocol = upstreamURL.protocol;
  requestURL.host = upstreamURL.host;
  requestURL.pathname = upstreamURL.pathname + requestURL.pathname;

  let newRequest;
  if (request.method === 'GET' || request.method === 'HEAD') {
    newRequest = new Request(requestURL, {
      cf: {
        cacheEverything: config.optimization.cacheEverything,
        cacheTtl: config.optimization.cacheTtl,
        mirage: config.optimization.mirage,
        polish: config.optimization.polish,
        minify: config.optimization.minify,
        scrapeShield: config.firewall.scrapeShield,
      },
      method: request.method,
      headers: request.headers,
    });
  } else {
    const requestBody = await request.text();
    newRequest = new Request(requestURL, {
      cf: {
        cacheEverything: config.optimization.cacheEverything,
        cacheTtl: config.optimization.cacheTtl,
        mirage: config.optimization.mirage,
        polish: config.optimization.polish,
        minify: config.optimization.minify,
        scrapeShield: config.firewall.scrapeShield,
      },
      method: request.method,
      headers: request.headers,
      body: requestBody,
    });
  }

  const fetchedResponse = await fetch(newRequest);

  const modifiedResponseHeaders = new Headers(fetchedResponse.headers);
  if (modifiedResponseHeaders.has('x-pjax-url')) {
    const pjaxURL = new URL(modifiedResponseHeaders.get('x-pjax-url'));
    pjaxURL.protocol = requestURL.protocol;
    pjaxURL.host = requestURL.host;
    pjaxURL.pathname = pjaxURL.path.replace(requestURL.pathname, '/');

    modifiedResponseHeaders.set(
      'x-pjax-url',
      pjaxURL.href,
    );
  }

  return new Response(
    fetchedResponse.body,
    {
      headers: modifiedResponseHeaders,
      status: fetchedResponse.status,
      statusText: fetchedResponse.statusText,
    },
  );
}

// eslint-disable-next-line no-restricted-globals
addEventListener('fetch', (event) => {
  event.respondWith(fetchAndApply(event.request));
});
```

# 2. Go to your domain setting, set worker rule

```
https://{yourDomain}/*
```
And select exist worker script

# 3. Add CNAME record, turn on Cloudflare proxied

CNAME record target is `{workerName}.{yourName}.workers.dev`

# 4. Test

Origin

https://mt3.google.com/vt/lyrs=s&x=106&y=52&z=7

Reverse Proxied

https://gmap.gitcafe.org/vt/lyrs=s&x=106&y=52&z=7

**Comment by h0wardch3ng** [comment]
> For China, google map is best :)
> I have use PyInstaller to create a exe file, but it reports virus when I update load to flightsim website. So I only give source code for that user. I recommended to use the exe file I made in release page.

I don't think so.

-------

The new ZSQD is available now.

In Google Map satellite

![image](https://user-images.githubusercontent.com/2175497/130351607-f97e5a2f-5db4-4353-87f8-d230f0ac12a3.png)


In Mapbox satellite

![image](https://user-images.githubusercontent.com/2175497/130351621-49681ade-9453-4acf-bf06-e4c2fc037d8c.png)

**Comment by derekhe** [comment]
Interesting, I see ChengDu is quite old image in mapbox

**Comment by h0wardch3ng** [comment]
@derekhe
Fine, ╮（╯＿╰）╭
If config file can set custom tile URL template, that's good.

Such as :

```
[map]
tile = https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?sku={yourSKUToken}&access_token={yourToken}
```

**Comment by derekhe** [comment]
> @derekhe
> Fine, ╮（╯＿╰）╭
> If config file can set custom tile URL template, that's good.
> 
> Such as :
> 
> ```
> [map]
> tile = https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?sku={yourSKUToken}&access_token={yourToken}
> ```

Please pull request :)

**Comment by Artoria2e5** [comment]
Well, I mean, the cntms codebase should have all the features you guys need with respect to configuing URL templates. Just do a refactor, add some header and proxy settings and everything...

**Comment by derekhe** [comment]
Thanks guys for discussion, will close this.

**Comment by a052** [comment]
> > For China, google map is best :)
> > I have use PyInstaller to create a exe file, but it reports virus when I update load to flightsim website. So I only give source code for that user. I recommended to use the exe file I made in release page.
> 
> I don't think so.
> 
> The new ZSQD is available now.
> 
> In Google Map satellite
> 
> ![image](https://user-images.githubusercontent.com/2175497/130351607-f97e5a2f-5db4-4353-87f8-d230f0ac12a3.png)
> 
> In Mapbox satellite
> 
> ![image](https://user-images.githubusercontent.com/2175497/130351621-49681ade-9453-4acf-bf06-e4c2fc037d8c.png)

mapbox is not that good in some places, see the pic below, the clouded area zoom in still clouded, can't see a thing.
<img width="960" alt="捕获1" src="https://user-images.githubusercontent.com/57518289/132132192-b37f8a05-04a5-428c-b038-a485e6573e4a.PNG">

and google do have ZSQD image, and quite new.
<img width="917" alt="捕获2" src="https://user-images.githubusercontent.com/57518289/132132222-ee291e4d-906b-48fb-af90-15547b0a4732.PNG">

after some days of comparing, bing google mapbox esri etc, I think best satallite image for china is still google.
