### ISSUE TITLE
Permission denied errno 13

### ISSUE THREAD

**Issue by okey7** [derekhe/msfs2020-google-map#130]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
No valid information, please checkout faq page for more details https://github.com/derekhe/msfs2020-google-map/wiki/FAQ
will close this one.
