### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by kaspervdh** [derekhe/msfs2020-google-map#132]
Images load for about 1 minute until most requests get blocked.
Switching to an other server helps of course, but it won't last long enough to load enough tiles.
Maybe iterate through all different servers so there is no throttling, or is that not possible technically?
Or maybe an option to use a proxylist.

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kh.ssl.ak.tiles.virtualearth.net.edgekey.net', port=443): Max retries exceeded with url: /tiles/mtx1202021101303?g=11361&tf=3dkh&n=z (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DAF5A93910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not respond correctly after a certain amount of time, or the connection failed because the connected host did not respond'))
127.0.0.1 - - [30/Nov/2021 21:17:54] "GET /tiles/mtx1202021101303?g=11361&tf=3dkh&n=z HTTP/1.0" 500 -

**Comment by derekhe** [comment]
Should be your internet connection problem

**Comment by kaspervdh** [comment]
> Should be your internet connection problem

I have a stable 300Mbps connection. I never have problems with Google services or Flightsimulator.
To me this seems more like the source is denying after x amounts of requests in x time.

**Comment by derekhe** [comment]
Please have a look at latest version and let me know. I added the load balancer.
