### ISSUE TITLE
443 Port in use

### ISSUE THREAD

**Issue by leeholden13** [derekhe/msfs2020-google-map#133]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
After executing the run.bat file as administrator an error message appears saying that 443 port in use, app will close.

**To Reproduce**
execute run.bat as administrator

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MOD Version 2.3.2
 - MSFS Version, MS Store

**Additional context**

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#443-port-is-occupied

**Comment by leeholden13** [comment]
Thanks for the prompt reply but it was not helpful.  You are obviously a highly skilled programmer, but I am not and don't know how or want to try to reprogram port use for other applications in order to use yours.  For normal point-and-click users like me your program should probably assign an unused port automatically or at least provide a way to change the port it uses.

**Comment by derekhe** [comment]
We can't change the default 443 port otherwise the whole solution won't work. Please find out the app using 443 and kill it.
