### ISSUE TITLE
[BUG] Failing to load scenery since latest update

### ISSUE THREAD

**Issue by PerryB413** [derekhe/msfs2020-google-map#137]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

Ever since the latest update where it picks a random server, I am getting a lot of 'default scenery' e.g. it's not loading so my ground looks horrible. PLEASE RESTORE ABILITY TO CHOOSE SERVER!

**To Reproduce**
Just use the product.

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: Win10Pro
 - MOD Version 2.3.3
 - MSFS Version, MS Store

**Additional context**

**Comment by derekhe** [comment]
You can keep previous version.

**Comment by PerryB413** [comment]
I will go into my archives and get it.  I hope that the future versions allow us to pick again, as without that I can't ever upgrade it again so if you make other improvements I won't get them.

**Comment by derekhe** [comment]
Sure, will return that back

**Comment by derekhe** [comment]
Close this as latest version has server choice.
