### ISSUE TITLE
"server"message

### ISSUE THREAD

**Issue by shfm1969** [derekhe/msfs2020-google-map#14]
srever console show message below repeatly, is this correct ??  Color of "GET /tiles/gen HTTP/1.1" 404 -" is ORANGE, I see "404" feel worrt.
127.0.0.1 - - [22/Aug/2021 10:07:22] "GET /tiles/gen HTTP/1.1" 404 -

and in fs2020 ,I didn't find enhancements.

**Comment by derekhe** [comment]
Don't worry about this, just ignore them.
Please also run in administrator mode and accept certificate error.
You should see the console printing a lot of messages when you navigate the internal map.

**Comment by shfm1969** [comment]
It is my fault, After set the "BING DATA WORLD GRAPHICS.." and "PHOTOGRAMMETRY", it is working now. Great!!
