### ISSUE TITLE
[BUG] KHMS servers will give a 404 error after sending too many requests—this will cause map tiles to not load properly during a long flight.

### ISSUE THREAD

**Issue by Tinh1000000** [derekhe/msfs2020-google-map#140]
I definitely appreciate and find usefulness with the patch you implemented to help with load-bearing between the servers—thank you!

The servers will respond with an empty request if you send too many requests to the KHMS map servers within a short period of time. They seem to be happening to those servers only, because they do not happen virtually at all if MT(№) servers are used in lieu. Perhaps using MT servers should work better at the moment until a workaround is issued?

**Comment by derekhe** [comment]
Thanks for feedback. I will let user still select servers and add a feature to load from random server to do load balance.

**Comment by Tinh1000000** [comment]
Sounds great for now, thanks for your work on this mod!

**Comment by mark007** [comment]
I got this today also mid flight through somewhere in the african sahara (I think thats where I was )

Downloading from: https://khms2.google.com/kh/v=908?x=282272&y=230679&z=19 {'https': ''}
127.0.0.1 - - [10/Dec/2021 23:29:27] "GET /tiles/akh1222100131210120222.jpeg?n=z&g=9590 HTTP/1.0" 404 -

Does it mean google doesn't have that particular tile, should the proxy revert to bing in that case or? On screen I could see some strange squares for sure, so I guess it was these tiles that showed the 404.

**Comment by Tinh1000000** [comment]
> I got this today also mid flight through somewhere in the african sahara (I think thats where I was )
> 
> Downloading from: https://khms2.google.com/kh/v=908?x=282272&y=230679&z=19 {'https': ''} 127.0.0.1 - - [10/Dec/2021 23:29:27] "GET /tiles/akh1222100131210120222.jpeg?n=z&g=9590 HTTP/1.0" 404 -
> 
> Does it mean google doesn't have that particular tile, should the proxy revert to bing in that case or? On screen I could see some strange squares for sure, so I guess it was these tiles that showed the 404.

IIRC, Google should use an upscaled tile of the same source, even though there is no native resolution for the zoom level. Since you were also using the KHMS servers (the ones where the bug only happens), I believe you did get rate-limited. If you have the latest version, you can select the **MT** servers from the _**Map Server**_ tab.

**Comment by mark007** [comment]
Ah great, the latest version / release, doesn't seem to have a Map Server tab, so I guess when thats released I will try that. Is that server not rate limited or is it the tool swapping between different servers to avoid the rate limit?

**Comment by Tinh1000000** [comment]
> Ah great, the latest version / release, doesn't seem to have a Map Server tab, so I guess when thats released I will try that. Is that server not rate limited or is it the tool swapping between different servers to avoid the rate limit?

The MT servers don't have the rate limiting issue since it's more lenient on the number of requests. Funnily, from what I have tried from before, even using a singular MT server didn't trigger any rate-limiting measures on my part.

The latest version should have the tab, are you sure you're using the 2.3.4 version from 2021-12-04? (You may need to delete your entire old directory and reinstall with the new version.)
![2021-12-11 00_28_35-MSFS 2020 Google Map](https://user-images.githubusercontent.com/8294050/145656784-5b90f58d-76a5-438c-b096-64d2f6d47382.png)

**Comment by mark007** [comment]
Ahh, I kept overwriting my old dir contents with the latest release to keep things like the cache, obviously this doesn't work so well. A clean directory works great. I'll try the mt server. Should it be the default, as its currently not?

**Comment by Tinh1000000** [comment]
> Ahh, I kept overwriting my old dir contents with the latest release to keep things like the cache, obviously this doesn't work so well. A clean directory works great. I'll try the mt server. Should it be the default, as its currently not?

At the moment, the app uses the KHMS servers by default (you'll have to go to the tab to change it to MT first), probably for performance reasons so the MT servers serve as a backup. I'm not the dev, so it's possible the default selection would change in a future release :>

By the way, the newest version no longer uses the built-in caching function, since MSFS's built-in rolling cache feature already serves the same purpose and having a separate one would already be redundant.

**Comment by mark007** [comment]
Ah OK so we should turn back on the msfs rolling cache, and it would be caching the google maps I guess as thats whats coming into it via the proxy, great.
