### ISSUE TITLE
[Feature] Request to deliver a single binary executable

### ISSUE THREAD

**Issue by mark007** [derekhe/msfs2020-google-map#142]
**Is your feature request related to a problem? Please describe.**
I love this project. I think it could be delivered a single, one file executable, instead of multiple files / python files etc.

**Describe the solution you'd like**
I would like you to consider using a great project, pyinstaller, to package up and build your logic into a single deliverable executable file. This would mean the zip we receive might only contain one executable, and possibly some configurable ini files.

**Describe alternatives you've considered**
none

**Additional context**
I have used pyinstaller for building standalone binaries of python packages and was very surprised how well it worked. I used staticx to remove the final dependency on a compatible libc library, so the final executable is truly standalone and requires no external files. This was for linux but I know it can also generate standlone, single file executables for windows.

**Comment by derekhe** [comment]
Thanks for the feedback. From beginning of this project, I'm consider using pyinstaller or py2exe to pack this software. But unfortunately, some antivirus reports vulnerabilities. I have tried many ways to work around it but failed at end, so I had to provide scripts which is not so good.
I'm working on a new version based on electron, so later on I can have more flexibilities.

**Comment by mark007** [comment]
Thanks for the reply. That sounds great.
