### ISSUE TITLE
[BUG] Stuck at loading screen

### ISSUE THREAD

**Issue by Angelo-1992** [derekhe/msfs2020-google-map#147]
After the last update, if I start the bat file before fs 2020, I get stuck in the middle of the simulator loading.
The only way to solve this is to start the simulator first and then the bat file. 
How can I manage to start the bat file before the simulator and not get stuck in the middle of loading? From what I understand this is the best method...

 - OS: Windows 10 64bit
  - MOD Version: v2.3.4
 - MSFS Version: Xbox App

**Comment by mark007** [comment]
Yeah I have the same issue. Does the game get stuck at around 55% loading for you? I can't kill it via alt-f4 or taskmgr. I can only kill via taskkill commands on a command prompt on a second desktop.

**Comment by derekhe** [comment]
Please check if any pop up window exist saying certificate issue? If yes, please click agree

**Comment by mark007** [comment]
I noticed it pop up at one point and the game loaded when it did. In other cases I cannot see it, even when doing alt-tab. Unless its still hidden behind other windows. Is there a way you guys can see the pop up window consistently.

**Comment by derekhe** [comment]
it should popup once and if you agree it, it won't show.
But if you don't agree it, it may not show again....

**Comment by mark007** [comment]
Yeah I clicked agree last time I saw it. For me the only way to get the game to consistently load now is to make sure to start the sim before starting the proxy tool. If its started afterwards it will not load, and gets stuck at 55% ~ on the main loading screen before reaching the games main menu.

**Comment by derekhe** [comment]
Ok, I see. Many people tell me about this but I can't reproduce on my local and can't find out why.

**Comment by mark007** [comment]
I wonder would any msfs logs give a clue. If useful I can look for some and share here, incase it gives a hint and some change in this tool would help remove it?

**Comment by derekhe** [comment]
I used proxifier + charles to monitor the requests from msfs.

**Comment by Angelo-1992** [comment]
My problem is identical to mark007's. The only difference is that I can close fs 2020 with taskmgr.
Unfortunately I am not able to use proxifier +, but if you explain me exactly what operations I have to do, I can also send you my log ;-)

**Comment by helibrewer** [comment]
I had this issue but the latest build seems to have resolved it.

**Comment by Angelo-1992** [comment]
Fortunately, I solved the problem. I started the bat file and then fs2020. Immediately after starting fs2020 I pressed the windows key and about halfway through the loading process two windows appeared regarding the certificates; I pressed Agree on both and the loading was completed :-)
