### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by gazzover67** [derekhe/msfs2020-google-map#15]
New problem. Looking at the command line, I see the 2 most common errors:

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

urllib3.exceptions.MaxRetryError`: HTTPSConnectionPool(host='kh.ssl.ak.tiles.virtualearth.net', port=443): Max retries exceeded with url: /tiles/gen (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

I installed the certificate from the folder "certs"

**Comment by derekhe** [comment]
What kind of proxy are you using?

**Comment by h0wardch3ng** [comment]
Check Server ca-certificates keep latest version, and check system date setting.

**Comment by gazzover67** [comment]
> What kind of proxy are you using?

I use this program without a proxy.

**Comment by gazzover67** [comment]
New command line message: 127.0.0.1 - - [22/Aug/2021 19:09:55] "GET /tiles/gen HTTP/1.1" 404 -

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/download/1.5.0/msfs2020-google-map-2021-08-22.zip

**Comment by gazzover67** [comment]
> Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/download/1.5.0/msfs2020-google-map-2021-08-22.zip

Thanks. Worked.
