### ISSUE TITLE
[BUG] CHANGE TITLE

### ISSUE THREAD

**Issue by Sitof** [derekhe/msfs2020-google-map#151]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
What's your problem?
