### ISSUE TITLE
[Feature/Suggestion] Re-enable nginx cache to not flood google.

### ISSUE THREAD

**Issue by IKatsu** [derekhe/msfs2020-google-map#152]
I'm flying around with the latest version and gauging by the constant stream of requests coming by it would appear that a lot of tiles are re-downloaded repeatedly since the nginx cache was disabled in the last version even though I have MSFS' rolling cache enabled.

Maybe re-enable the cache to offload the google servers so we won't upset anyone there ?
Or add an optional configuration parameter in the gui for it. Better safe than sorry with this IMHO.

(Or I'm not seeing this correctly and everything's fine ;) )

**Comment by derekhe** [comment]
I'm thinking about this. In game cache give more control on the cache.
