### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by joetrills** [derekhe/msfs2020-google-map#153]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
The game crashes after taking off ingame. Issues like the game loading and crashing started when I first installed the mod. I removed the files but the game does not work.

**To Reproduce**
Load up the game, take off, and wait a few minutes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
MSFS2020 Steam Edition 

**Additional context**
N/A

**Comment by joetrills** [comment]
I also looked for the lines of code to delete but I could not find them.

**Comment by Nestirium** [comment]
If you are using Nvidia, and your driver is the latest, the cause is not google maps, it is the driver.
The game crashes with the latest nvidia driver, you have to revert to the old one.
497.09
https://piunikaweb.com/2021/12/04/microsoft-flight-simulator-crashes-after-updating-nvidia-drivers/

**Comment by Evovita** [comment]
After upgrading from Version **497.09 to 497.29** of the _GeForce Game Ready Driver_, I no longer experience crashing to desktop when commencing a flight.
