### ISSUE TITLE
LOD Tiles pretty bad around EGCC

### ISSUE THREAD

**Issue by Steveyram** [derekhe/msfs2020-google-map#154]
The app is amazing, I've been using it for a while, and I love to fly 747's, however the last few days I've been flying, especially around the UK, the LOD is pretty bad.

As you get upto 7,000ft, the tiles a few miles away seem to be autogen squares and seem to morph as you fly towards them, not sure if this problem has been reported but one way to see what I mean is start a flight from EGCC (Manchester) and you will see what I mean.

I've tried testing from all servers and when I test the servers, it gives me a pretty good ping (0.07secs).

Please let me know if anyone else is getting the same problem.

**Comment by derekhe** [comment]
Please try run the mod BEFORE msfs2020

**Comment by Steveyram** [comment]
Thanks for your fast reply.

I've tried but the sim doesn't load properly and hangs, however I'll give it another few tries and get back to you if I succeed :-)

**Comment by Steveyram** [comment]
I have successfully loaded up MSFS after running the program, however I'm still getting the LOD problem, I've put the picture below at what I'm getting:

![Capture](https://user-images.githubusercontent.com/95755172/145217003-08b34d98-3d4c-45d4-8deb-10287fa70de2.JPG)

It may be just this part of the world, however I've just started a flight from Manchester - Belgrade so I will let it run and see if it eventually kickstarts, however I've never had this before.

Not sure if you want to replicate the flight and see for yourself?, it does look pretty ugly however I'm hoping it will go to normal shortly

**Comment by Steveyram** [comment]
Also after getting to a certain point I get this line of, what seems to be autogen textures and anything below it goes back to normal, it does make me think it could be something to do with the LOD bug that Asobo mentioned the more northerly you go it kicks in?, here's the line:

![Capture](https://user-images.githubusercontent.com/95755172/145219693-84082b89-8bd7-4568-8118-759a8936a751.JPG)

**Comment by derekhe** [comment]
The autogen map is incorrect. You can try clear the rolling cache and try again. You can check in google map if this location has same issue.

**Comment by Steveyram** [comment]
I don't have rolling cache on and it looks fine in google maps as it's the UK, that's the confusing thing.

I will keep experimenting and hopefully I will find the reason why :-)

**Comment by derekhe** [comment]
Ok, if you start the mod before msfs2020, it shouldn't have any autogen areas (but when loading the image fail, it may load autogen areas)

**Comment by Steveyram** [comment]
I've tried everything with this but I'm sure there is a 'square' of really bad LOD texture covering from Northern England down to Birmingham, I've deleted cache (several times) but I'm still getting pop-up squares appearing.

I'm wondering any one else can test this area?, Maybe from Birmingham, England and fly up North or in and around Manchester.

Really strange!

**Comment by derekhe** [comment]
You can enable developer mode and show the location, so I can have a try there.

**Comment by Steveyram** [comment]
If you take off from EGCC (Manchester, UK), if you turn your plane either northerly or easterly, as you climb upto 5,000ft, you will notice it straight away...make sure you have a sunny day as it's always horrible weather here in the UK ;-)

I've tried using Bing maps and the popping/morphing isn't apparent, but with the google maps also if you fly south from Manchester, you will notice when you get to Birmingham there is a line that goes as far as the eye can see and after that line the morphing/popping of google textures will stop, it's really strange!!

**Comment by derekhe** [comment]
Do you mean the line here?
![FlightSimulator_hoaho1iCFt](https://user-images.githubusercontent.com/1734077/145387665-0c92a213-246f-4b62-b0b4-c4a288ba2f9f.png)

Please give me the actual location so I can find it. I can't find your place.

![image](https://user-images.githubusercontent.com/1734077/145390881-31e8987d-3685-4389-adc7-c7f45fa3379f.png)

**Comment by Steveyram** [comment]
Thanks for checking!, I'm currently at work so unable to access my computer but I'll try to show you when I get home.

Most of my problem is when the plane is actually moving and the tiles 'change' below me over a certain area, however when I'm out of that area the morphing stops, it stretches most of North/Central England!

I'm not sure if it's my files which I might need to look at as yours looks better than mine does so this may be the case

**Comment by Steveyram** [comment]
Apologies for my reply, I've been busy at home.

I've taking as much info as possible, basically I've tried flying down the 'line' that seperates very good LOD with google maps and not-so-good LOD:

![Capture](https://user-images.githubusercontent.com/95755172/145643357-429ff842-65ac-4cf1-9f64-dc6875a8a685.JPG)

When I fly over the area, it looks fine, as you can see from the picture, but in the distance, on the right hand side is the bad LOD and on the left is the great LOD...as I fly towards it, it seems to morph into the google maps we all know but froma  distance it looks ugly...in the corner on the top is my navigation area so you can pick up where I'm flying!

Below is where my plane is on the map...sorry about my rubbish plane drawing but It shows where I was flying and the line that seems to seperate the good LOD to the not-so-good LOD.

I hope this makes sense:

![Capture2](https://user-images.githubusercontent.com/95755172/145643643-0c51aea4-58dd-4e5b-addc-b1de392c18bb.JPG)

**Comment by derekhe** [comment]
Here are the screenshots I took from from the same location. The place are good.
You can try the following:
* Before you turn on the mod, clear everything inside the "cache" folder to prevent caching.
* Switch to "mt" server
* Start the mod before you start MSFS2020.

![python_Udj7fKKPmk](https://user-images.githubusercontent.com/1734077/145668556-9a769237-7122-43fb-b35c-1dcc9f16c977.png)
![FlightSimulator_xDUIhjb4O0](https://user-images.githubusercontent.com/1734077/145668558-d7f8d77d-92ca-46ae-b3fb-132936b075e9.jpg)
![FlightSimulator_vAF8I8KGwf](https://user-images.githubusercontent.com/1734077/145668559-e4231047-efb2-425e-ba06-be452f0c2680.jpg)
![FlightSimulator_3bCMZ2yJHS](https://user-images.githubusercontent.com/1734077/145668560-3eaf2c83-26a1-4be3-a98d-e6972911330d.jpg)
![FlightSimulator_akl2M8LjeK](https://user-images.githubusercontent.com/1734077/145668562-7449df78-e47e-4665-b4e9-8a46b6bd9cd1.jpg)
![FlightSimulator_1gbi4I2M0F](https://user-images.githubusercontent.com/1734077/145668563-0c38188d-a3e7-4672-9e04-2b09cf05ce30.jpg)
![FlightSimulator_K6PQQrnDHx](https://user-images.githubusercontent.com/1734077/145668564-6693a650-0fa0-4470-beff-05930eb2c4c5.jpg)
![FlightSimulator_YpXkTKbPXR](https://user-images.githubusercontent.com/1734077/145668565-4c574059-0762-4537-9515-6d336deb78c3.jpg)
![FlightSimulator_Ta7UF2mfSD](https://user-images.githubusercontent.com/1734077/145668567-b92f98f6-dfce-4825-b62a-889e987689ad.png)
![FlightSimulator_gjI8QI6vwG](https://user-images.githubusercontent.com/1734077/145668570-b606a500-e8d1-43d5-886f-d62e8d690320.jpg)

**Comment by Steveyram** [comment]
I'm pleased that it my setup and not the app that's showing this, when you say clear everything in side the cache folder, where do I find this?, I don't have rolling cache enabled so I cant delete anything any game

**Comment by derekhe** [comment]
![image](https://user-images.githubusercontent.com/1734077/145669475-636a0485-244f-4597-b537-d0abf89f5cd5.png)

**Comment by derekhe** [comment]
Delete these files.

**Comment by Steveyram** [comment]
Ah!, I can't see this folder...

![image](https://user-images.githubusercontent.com/95755172/145669762-ae5c1ad9-9978-434b-900b-4c00d17679a2.png)

This is what I have

**Comment by derekhe** [comment]
Ok, you are using latest version. Don't worry about that folder.
