### ISSUE TITLE
[BUG] Can't close apps that use port 443

### ISSUE THREAD

**Issue by aspireflight** [derekhe/msfs2020-google-map#158]
**Describe the bug**
I cant close apps that use port 443 because they are mostly system processes how can I get through this?
**To Reproduce**

Launch the MOD

**Screenshots**
![image](https://user-images.githubusercontent.com/68855928/145422690-fed85208-6f0d-4e82-9af2-a6b16bc8b865.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
  - MOD Version 2.3.4
 - MSFS Version, MS Store

**Additional context**

**Comment by Nolema** [comment]
Vmware hostd.exe use 443

**Comment by derekhe** [comment]
Please find this out the app using 443, I can't give any solution here.
