### ISSUE TITLE
Add systray function

### ISSUE THREAD

**Issue by h0wardch3ng** [derekhe/msfs2020-google-map#16]
https://github.com/phuslu/taskbar

[server-tray.zip](https://github.com/derekhe/msfs2020-google-map/files/7027225/server-tray.zip)

Icon from https://www.flaticon.com/free-icon/map_854901?term=map&page=1&position=32&page=1&position=32&related_id=854901&origin=search

**Comment by derekhe** [comment]
I have no time to do this, you can do it by your own or have a PR
