### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Tank33au** [derekhe/msfs2020-google-map#163]
When I press the Start button this is what happens
![2021-12-12 14_41_13](https://user-images.githubusercontent.com/35152592/145699347-48f3f4f9-442e-40ba-bfd7-23bca8bbb9fe.png)

**Comment by derekhe** [comment]
For hosts related issue, first look at: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-related-issue
