### ISSUE TITLE
按照教程加载cmd出现错误

### ISSUE THREAD

**Issue by JIAOZIJIAN1** [derekhe/msfs2020-google-map#168]
按照您在bilibili的教程，完全遵循您的教程出现py不能解码，请问如何解决
![1](https://user-images.githubusercontent.com/96459318/146871099-8b29cd70-2ada-453e-9858-d8b00e26ca2a.png)

**Comment by derekhe** [comment]
![image](https://user-images.githubusercontent.com/1734077/146936163-10dd3c27-48af-4aa0-90f9-e55f8dbacd30.png)

请将区域设置改为英文，要不然自动导航也无法用。

**Comment by derekhe** [comment]
改为英文以后会影响一些软件的使用，比如出现乱码等，比较烦。但模拟飞行2020有中文版以后再说吧。Python的这个问题后续我在新版本中解决。

**Comment by JIAOZIJIAN1** [comment]
> 改为英文以后会影响一些软件的使用,比如出现乱码等,比较烦。但模拟飞行2020有中文版以后再说吧Python .的这个问题后续我在新版本中解决。

感谢，已经解决了
