### ISSUE TITLE
Latest update won't work for me

### ISSUE THREAD

**Issue by TacticalBacon86** [derekhe/msfs2020-google-map#176]
I downloaded the latest update, and now it won't work. I used the old version just fine with the .bat file and so forth. Now the new version is telling me it cannot connect to Google because of my proxy settings. I'm not a computer guy. I'm  a pilot (real world), and I don't have the slightest clue what I need to do for setting up a proxy. Information I'm finding on the web is vague at best (for people who aren't computer people). Can anyone advise on what I need to do? Thank you.

**Comment by derekhe** [comment]
Thanks for the feedback. Please still try use the old version and keep tune for the newest version.
I'm trying to fix the problem.

**Comment by derekhe** [comment]
Btw, you can check if the proxy setting is empty like this:
![image](https://user-images.githubusercontent.com/1734077/147896381-619be013-c78a-4ef7-8ba9-004f474b6a94.png)

**Comment by derekhe** [comment]
Could you give me any screenshots for the new version so I can try to find out why

**Comment by TacticalBacon86** [comment]
Yes, that field was empty.

**Comment by TacticalBacon86** [comment]
I actually deleted it. I was fortunate enough to find an older version I
didn’t delete so I reverted back to it.

**Comment by derekhe** [comment]
No worries, I'm trying to fix it. Please stay tunned to latest version.

**Comment by TacticalBacon86** [comment]
Thank you! Your efforts are MUCH appreciated, and the app adds phenomenal
VFR scenery to FS. I can’t tell you enough how so many of us have been
enjoying your work.

**Comment by derekhe** [comment]
Please try latest alpha-0.1 version in flightsim.to website :)
