### ISSUE TITLE
the fallback function

### ISSUE THREAD

**Issue by Nibbio1976** [derekhe/msfs2020-google-map#20]
the fallback function loads Bing images

**Comment by derekhe** [comment]
what do you mean?

**Comment by Nibbio1976** [comment]
ip addresses are from Bing

![Screenshot (444)](https://user-images.githubusercontent.com/89440744/130643821-66a0bd5b-bd8b-4ec3-a479-c8279a1502c8.png)

**Comment by Nibbio1976** [comment]
for those who don't need the proxy, I deleted the fallback function and changed:
@ app.route ("/ tiles / akh <path>")
@ app.route ("/ tiles / a <path>")

**Comment by derekhe** [comment]
What's fine, some color correction data is loading from khstorelive
