### ISSUE TITLE
打开后显示如下，然后自动打开了github项目页面

### ISSUE THREAD

**Issue by 930175620** [derekhe/msfs2020-google-map#21]
![1](https://user-images.githubusercontent.com/38825477/130629889-60673484-e72b-4590-97ce-c1613847dbe5.png)
打开后显示如下，然后自动打开了github项目页面

**Comment by Virmba** [comment]
把占用443端口的应用进程杀掉

**Comment by derekhe** [comment]
This is a common issue, please close any software has 443 port.
