### ISSUE TITLE
antivirus delete the both exe files

### ISSUE THREAD

**Issue by GOZARCK** [derekhe/msfs2020-google-map#22]
antivirus detect like trojan virus. Virus total found 14 antivirus detect virus in those files.

**Comment by h0wardch3ng** [comment]
https://github.com/derekhe/msfs2020-google-map/issues/18

**Comment by GOZARCK** [comment]
uninstalling the antivirus, or temporarily disabling or creating an exception for those executable files, is a temporary solution and does not seem like a good practice to me, they could modify the source code so that this does not happen

**Comment by derekhe** [comment]
I have no idea,  it is mentioned in https://github.com/pyinstaller/pyinstaller/labels/antivirus-false-positives
