### ISSUE TITLE
无法加载谷歌卫星图

### ISSUE THREAD

**Issue by faker320** [derekhe/msfs2020-google-map#24]
正常情况下游戏会提示证书，点是之后就能加载谷歌卫星图了，但是现在突然不提示证书了，程序运行情况如下
![image](https://user-images.githubusercontent.com/85487730/131450800-49af6d18-3ebb-4a85-9413-d1f854eaabc1.png)

**Comment by derekhe** [comment]
请尝试最新的2.0.0版本，应该可以解决问题

**Comment by faker320** [comment]
2.0.1版本运行run.bat之后命令行一闪而过，没法一直运行

**Comment by KAPTOHKA** [comment]
HOODLUM not work?

**Comment by faker320** [comment]
It works now!


------------------ 原始邮件 ------------------
发件人: hesicong ***@***.***&gt;
发送时间: 2021年9月15日 22:02
收件人: derekhe/msfs2020-google-map ***@***.***&gt;
抄送: faker320 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[derekhe/msfs2020-google-map] 无法加载谷歌卫星图 (#24)





 
Please test the latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.0.3
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sdysgjzt** [comment]
> Please test the latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.0.3

从2.03版本开始，都是一闪而过，8-22版本是正常的。求助作者

**Comment by sdysgjzt** [comment]
> Please test the latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.0.3

我是把梯子架在路由器上的，默认可以上google地图，8-22版本时候就改了一个URL为本机IP就顺利登陆了。后面由于游戏升级无法正常使用，今天看到您升级了版本测试了2.00-2.03，均是一闪而过。求作者赐教解决办法，谢谢。

**Comment by derekhe** [comment]
请确保你仔细阅读以下说明：

下载压缩包并解压
- 必须！！！安装从这里安装Python( https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe )，不要使用微软商店的版本全部使用默认配置
管理员权限运行run.bat启动程序，设置好proxy并测试代理，确保代理正常使用。
启动模拟飞行，保留命令行的黑窗口
保证游戏中在线地图功能打开（BING DATA WORLD GRAPHICS和PHOTOGRAMMETRY），否则只能获得离线地图
尽情享用吧
