### ISSUE TITLE
UnicodeDecodeError与证书错误

### ISSUE THREAD

**Issue by MasonZhangZmx** [derekhe/msfs2020-google-map#3]
![15b28bd079dd1674aad3075756fbdbe](https://user-images.githubusercontent.com/89013440/129837802-9ad630bb-4ac6-432a-af15-1ea5a14acd25.jpg)
不好意思，靠录像截到的，有点糊。。。
修改hosts那一段代码不知道为什么会报错（如图），删掉这段代码手动修改运行的话服务器能够启动
不过会出现:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
然后游戏中会出现data stream带宽过小已关闭串流。
于是目前卡在这里了。。。

**Comment by MasonZhangZmx** [comment]
如果把证书验证也关掉的话会出现
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='kh.ssl.ak.tiles.virtualearth.net', port=443): Read timed out. (read timeout=30)

**Comment by derekhe** [comment]
这个是中文系统编码的问题，可以把系统调成英文的。目前MSFS2020的不支持中文的系统，请在语言设置中改为英语
![image](https://user-images.githubusercontent.com/1734077/129920095-88ce6421-3fac-459a-9e6c-a6387ea23c86.png)

证书问题请试试最新版本，参见release

**Comment by MasonZhangZmx** [comment]
原来是hosts文件之前修改的时候编码变成了UTF8 with BOM，改回来就好了，另外我那天又检查了一下，发现我这边的地图请求是以/tiles/a1320200230.jpeg结尾的，并没有akh，于是小改了一下代码。效果很棒！太感谢了！新证书很好用！
