### ISSUE TITLE
How to return to default Bing imagery

### ISSUE THREAD

**Issue by EricFlight** [derekhe/msfs2020-google-map#31]
Before I try this (which seems amazing as I prefer Google imagery over Bing).....

How do you return to the default photogrammetry of MSFS 2020 if you install this msfs2020-google-map mod?

Please let us know just in case we want to turn it back to the original Bing data

Thanks
Eric

**Comment by toorop** [comment]
Hi,

Normally, when you shutdown the app,  it removes entries in your hosts files automatically. 
If not do, it manually as explained here:
 https://github.com/derekhe/msfs2020-google-map/blob/main/README.EN.md#steps-for-usage

**Comment by derekhe** [comment]
@EricFlight Please follow @toorop . It is written in readme.
