### ISSUE TITLE
Scenery I think loads but says connection lost and then goes offline without reconnect

### ISSUE THREAD

**Issue by EricFlight** [derekhe/msfs2020-google-map#32]
It seems that the Google Maps imagery loads but only in certain places...it's like a mixture of satellite data but then default non-photogrammetry scenery like it can't load certain places.....no clue on how to fix it.

I also had to manually insert what needed to be in the hosts file to make it work. The run.bat didn't seem to do anything to add to the hosts file or to make it work.

Simulator says it disconnected from photogrammetry, then says connected again on the screen, then says it kicks me offline and I have to go back to the menu to make it have Bing data on.
![Google Scenery](https://user-images.githubusercontent.com/70857916/133913380-ecc7d81c-eea3-494a-aef4-38f86fc5c667.jpg)
![Google Half and Half](https://user-images.githubusercontent.com/70857916/133913382-d6e0b2cb-d720-4f3a-b9b7-2c380abadee9.jpg)

**Comment by EricFlight** [comment]
Default Bing Photogrammetry in same area as 1st photo abov
![Bing Scenery](https://user-images.githubusercontent.com/70857916/133913710-81c7b254-cf85-4f06-a6d0-b1c59ae07f74.jpg)
e

**Comment by derekhe** [comment]
Do you use a proxy to access google?
Do you run in administrator mode?
Do you run latest version?

**Comment by EricFlight** [comment]
No..I don't use a proxy
Yes
Yes

**Comment by derekhe** [comment]
Can you give me the screen shot from the blank console window?
