### ISSUE TITLE
A Small tip/小贴士

### ISSUE THREAD

**Issue by PREChairman** [derekhe/msfs2020-google-map#33]
mfs的procedural buildings分为两种，一种是基于OSM数据生成的较精细模型，另一种是在本地识别卫星图并生成的简易模型。在使用本脚本后，OSM的建筑并不会消失，但是卫星图识别的建筑会消失（似乎是SU5后无法再识别第三方卫星图）。而大部分自动生成的机场航站楼是基于卫星图的，请谨慎使用。

There are two types of procedural buildings in msfs, including osm buildings and autogens which are generated with local satellite images. It seems that simupdate 5 messed up almost everything related to aerial maps,including wrong colors while building package and lack of autogens that were available with non-bing satellite images back to simupdate 4. With a number of default airport using autogen terminals, I strongly recommend you to think twice before using it.

**Comment by derekhe** [comment]
但是卫星图识别的建筑会消失（似乎是SU5后无法再识别第三方卫星图）~~~我没有观察到卫星图识别的建筑物的消失，能给我一个地点（经纬度）我来看下是什么问题呢？

**Comment by derekhe** [comment]
@PREChairman hello？

**Comment by PREChairman** [comment]
ZSSS周边看看呢

**Comment by derekhe** [comment]
可否帮忙提供对比截图
