### ISSUE TITLE
如何确认127.0.0.1后面的端口号（−＿−；）

### ISSUE THREAD

**Issue by Nolema** [derekhe/msfs2020-google-map#34]
不好意思啊，用的客户端是clash，管理员权限启动bat文件后不知道ip那里要输什么。。

**Comment by derekhe** [comment]
你可以先把代理那个清除试试，Test Connection试试。
clash的话，你可能自己去看下socks5的地址是什么

**Comment by Nolema** [comment]
> 你可以先把代理那个清除试试，Test Connection试试。 clash的话，你可能自己去看下socks5的地址是什么

端口号百度到了，7890，测试连接ok，然后运行提示没有找到nginx.exe进程，使用的是msfs2020-google-map-2021-09-28这个版本

**Comment by derekhe** [comment]
应该不至于，请不要放到任何有中文的目录

**Comment by Nolema** [comment]
> 应该不至于，请不要放到任何有中文的目录

我参照之前的issues把vmware-hostd.exe这个进程干掉以后手动启用nginx.exe后可以了，非常感谢
