### ISSUE TITLE
Add "ArcGIS Imagery"...

### ISSUE THREAD

**Issue by KAPTOHKA** [derekhe/msfs2020-google-map#44]
Add "ArcGIS Imagery" to the server selection, some regions here are newer...
[src_Msfs2020_Arcgis.zip](https://github.com/derekhe/msfs2020-google-map/files/7449911/src_Msfs2020_Arcgis.zip)

Source: https://www.avsim.su/forum/topic/225606-google-map-%D0%B8-arcgis-imagery-%D0%B4%D0%BB%D1%8F-msfs2020/?_fromLogout=1&_fromLogin=1

**Comment by derekhe** [comment]
Thanks, I will go and have a look
