### ISSUE TITLE
Hosts file resolve failed

### ISSUE THREAD

**Issue by derekhe** [derekhe/msfs2020-google-map#47]

**Comment by gerryB1950** [comment]
I can't find C:\windows\system32\drivers\etc\hosts file on my system

**Comment by gerryB1950** [comment]
This is what I found in my hosts file
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

#	127.0.0.1       localhost
#	::1             localhost

Thank you for your help looks like a great product

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by gerryB1950** [comment]
Hi:
I have tried version 2.2.5 and I don't get the error message, but the
program won't work.  I have turned off the antivirus and firewall and it is
still not working.

Thank you,
Gerry

**Comment by derekhe** [comment]
Can you do a screen recording about all you doing and let me have a look?

**Comment by gerryB1950** [comment]
Hi:
I don't know how to do a video screenshot, here is a screenshot of after I
open (with admin rights) and press the Run button.

Thank you,
Gerry

**Comment by derekhe** [comment]
There is no screenshots?

**Comment by gerryB1950** [comment]
sorry
