### ISSUE TITLE
error message "Generate nginx file failed"

### ISSUE THREAD

**Issue by viniciusbrei** [derekhe/msfs2020-google-map#53]
Congratulations for the effort to develop this nice mod! 
After starting the run.bat file as administrator, I click "run", and receive the error message "Generate nginx file failed". It seems the mod is not loading Google Maps images. 
Also, I'm getting another error message in the run.dat output "dns.exeption.Timeout: The DNS operation timed out after 5.4 seconds".
Any suggestions?
Thanks!

**Comment by derekhe** [comment]
Seems it has issue finding DNS resolve. Do you have issue access 8.8.8.8 or 8.8.4.4

**Comment by viniciusbrei** [comment]
I'm sorry, I did not understand your answer. Should I search for access 8.8.8.8 or 8.8.4.4?

**Comment by derekhe** [comment]
Sorry, I mean you may have access issue for 8.8.8.8 or 8.8.4.4 so that the DNS can't be resolved.
I will more common servers and please stay tunned for latest version

**Comment by derekhe** [comment]
Please try this version, I added more DNS server, may solve this problem.
https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.4

**Comment by viniciusbrei** [comment]
I've updated the version to 2.2.4 and got this new error message:
[error.pdf](https://github.com/derekhe/msfs2020-google-map/files/7521559/error.pdf)

**Comment by derekhe** [comment]
Thanks, I think it is a DNS issue, I'm trying to find out.

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by derekhe** [comment]
@viniciusbrei any fix?

**Comment by derekhe** [comment]
Also ,please try: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.6

**Comment by derekhe** [comment]
@viniciusbrei did it fix?

**Comment by viniciusbrei** [comment]
Unfortunately, it's not working. The mod is not crashing anymore, but I does not load Google Maps in MSFS 2020.

**Comment by derekhe** [comment]
Please try latest version

**Comment by derekhe** [comment]
@viniciusbrei fixed?

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2
