### ISSUE TITLE
embedded null character

### ISSUE THREAD

**Issue by bl73** [derekhe/msfs2020-google-map#54]
Hello I need some help :

the soft doesnt start, it stay on "stopped"

last line in cmd.exe is : ValueErrror: embedded null character

V2021.11.10 , same issue without antivirus & firewall

thanks for your help :)

**Comment by derekhe** [comment]
Please post the C:\windows\system32\drivers\etc\hosts file as attachment here. Some users has this issue but I can't reproduce.

**Comment by bl73** [comment]
[hosts.zip](https://github.com/derekhe/msfs2020-google-map/files/7520086/hosts.zip)
here's my host file

**Comment by derekhe** [comment]
I see, the hosts file has been modified by Docker Desktop and it may save it using BOM, the begin of this file looks like this: 

![image](https://user-images.githubusercontent.com/1734077/141294390-754d6181-963d-4232-b2ed-4c11aff63ae2.png)

In this case, you can delete the hosts file (backup it in case), and then it should be ok.

**Comment by derekhe** [comment]
Interesting, I find the root case: https://github.com/docker/for-win/issues/6038
It is caused by docker's bug

**Comment by bl73** [comment]
ok i have deleted my host file, and create à new one with the default values
now the issue is unabletiwritehost
![Capture](https://user-images.githubusercontent.com/57721948/141300718-f30b00d3-fef8-48cc-aa09-4afdc6bc4a7d.JPG)

**Comment by derekhe** [comment]
interesting, just delete the file, the app will create one. Also please run in admin mode and turn off some antivirus (some antivirus will prevent change hosts files)

**Comment by bl73** [comment]
ok it runs ! new host file was created, and i had also to create a kaspersky exception to make it connected.
and I have deleted docker desktop ....
Thanks a lot for helping !!
