### ISSUE TITLE
Stuck at "health check passed"

### ISSUE THREAD

**Issue by franmolders** [derekhe/msfs2020-google-map#55]
After executing "run.bat" with administrative privileges, the process on CMD windows stops at "health check passed", and no imagery is added to MSFS 2020 whatever I choose as an option: servers,...I am in Spain, no Google proxy needed.
Thank you!

**Comment by derekhe** [comment]
Please look at the configuration in game: https://www.youtube.com/watch?v=Lk7GK5XLTt8
Especially the rolling cache is very important, if you turn it on, please turn it off and clear the cache.

**Comment by lordmonish** [comment]
i do have the same issue , can you be please be more specific about what to do sir ?

**Comment by derekhe** [comment]
I think it is a DNS issue, I'm trying to find out.

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by franmolders** [comment]
Thank you, problem fixed!

**Comment by whityini** [comment]
I am also stuck at 'health check passed', running latest version, rolling cache off.
Thank you
