### ISSUE TITLE
[BUG] DOES not seem to work looks good but when you terminate says exit with y it fails when run again it gives port error and total restart of computer needed

### ISSUE THREAD

**Issue by anthony1956** [derekhe/msfs2020-google-map#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
Please try to kill the nginx.exe in task manager

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5
And please click "Stop" before you close, I added tips there in new version

**Comment by derekhe** [comment]
@anthony1956 did it fix?

**Comment by Mustang54GT** [comment]
I have the same issue. I've tried killing nginx in task manager but it restarts under a new PID after you kill it.

**Comment by derekhe** [comment]
I will close this since long term no response.
