### ISSUE TITLE
[BUG] doesn't work

### ISSUE THREAD

**Issue by lucamors1** [derekhe/msfs2020-google-map#57]
For me the mod doesn't work. No maps being loaded and not maps being visualized in the simulator
The mod loads correctly, but don't load maps.
I looked at the log files under the nginx folder and into the error.log it's showing :
2021/11/11 19:26:32 [notice] 256#5576: using the "select" event method
2021/11/11 19:26:32 [notice] 256#5576: using the "select" event method
2021/11/11 19:26:32 [notice] 256#5576: nginx/1.21.3
2021/11/11 19:26:32 [notice] 256#5576: nginx/1.21.3
2021/11/11 19:26:32 [info] 256#5576: OS: 260200 build:9200, "", suite:100, type:1
2021/11/11 19:26:32 [notice] 256#5576: start worker processes
2021/11/11 19:26:32 [notice] 256#5576: start worker processes
2021/11/11 19:26:32 [notice] 256#5576: start worker process 9296
2021/11/11 19:26:32 [notice] 256#5576: start worker process 9296
2021/11/11 19:26:32 [notice] 9296#7808: nginx/1.21.3
2021/11/11 19:26:32 [notice] 9296#7808: nginx/1.21.3
2021/11/11 19:26:32 [info] 9296#7808: OS: 260200 build:9200, "", suite:100, type:1
2021/11/11 19:26:32 [notice] 9296#7808: create thread 6052
2021/11/11 19:26:32 [notice] 9296#7808: create thread 6052
2021/11/11 19:26:32 [notice] 9296#7808: create thread 5468
2021/11/11 19:26:32 [notice] 9296#7808: create thread 5468
2021/11/11 19:26:32 [notice] 9296#7808: create thread 1924
2021/11/11 19:26:32 [notice] 9296#7808: create thread 1924
2021/11/11 19:26:44 [error] 9296#6052: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/11 19:26:44 [error] 9296#6052: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/11 19:26:44 [error] 9296#6052: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/11 19:26:44 [warn] 9296#6052: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/11 19:26:44 [warn] 9296#6052: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/11 19:26:44 [info] 9296#6052: *1 client 127.0.0.1 closed keepalive connection

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by lucamors1** [comment]
I tried, same error in the log, and no google maps showing in simulator :
2021/11/12 11:51:44 [notice] 5732#11032: using the "select" event method
2021/11/12 11:51:44 [notice] 5732#11032: using the "select" event method
2021/11/12 11:51:44 [notice] 5732#11032: nginx/1.21.3
2021/11/12 11:51:44 [notice] 5732#11032: nginx/1.21.3
2021/11/12 11:51:44 [info] 5732#11032: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 11:51:44 [notice] 5732#11032: start worker processes
2021/11/12 11:51:44 [notice] 5732#11032: start worker processes
2021/11/12 11:51:44 [notice] 5732#11032: start worker process 4400
2021/11/12 11:51:44 [notice] 5732#11032: start worker process 4400
2021/11/12 11:51:44 [notice] 4400#11148: nginx/1.21.3
2021/11/12 11:51:44 [notice] 4400#11148: nginx/1.21.3
2021/11/12 11:51:44 [info] 4400#11148: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 11:51:44 [notice] 4400#11148: create thread 5520
2021/11/12 11:51:44 [notice] 4400#11148: create thread 5520
2021/11/12 11:51:44 [notice] 4400#11148: create thread 736
2021/11/12 11:51:44 [notice] 4400#11148: create thread 736
2021/11/12 11:51:44 [notice] 4400#11148: create thread 10272
2021/11/12 11:51:44 [notice] 4400#11148: create thread 10272
2021/11/12 11:51:55 [error] 4400#5520: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 11:51:55 [error] 4400#5520: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 11:51:55 [error] 4400#5520: *1 connect() failed (10061: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 11:51:55 [warn] 4400#5520: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 11:51:55 [warn] 4400#5520: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 11:51:55 [info] 4400#5520: *1 client 127.0.0.1 closed keepalive connection
2021/11/12 11:51:55 [info] 4400#5520: *4 client 127.0.0.1 closed keepalive connection

**Comment by lucamors1** [comment]
![image](https://user-images.githubusercontent.com/94136747/141457556-aa76a051-9856-469f-8f6d-100160a60f35.png)
![image](https://user-images.githubusercontent.com/94136747/141457581-2be22157-6bc5-4fe9-82fd-91656cf0438b.png)

**Comment by derekhe** [comment]
Did you turn on the online data feature in game? Please check the config, which mentioned in the https://youtu.be/Lk7GK5XLTt8?t=168

**Comment by lucamors1** [comment]
yes, online functionality is enabled. i don't know if matters, but at the start of the simulator, the simulator checks for updates and message me telling that cannot update the game and i must click on "Switch Offline" to proceed and start. If i click the other option, "OK", he stucks searching for updates.. i don't know if this is related to the problems of the mod not working..

**Comment by derekhe** [comment]
yes, if you switch to offline, satellite images will not show, please ignore it.
Btw, suggest you to watch the youtube video see anything missing: https://www.youtube.com/watch?v=E11XsrBdzcg
Please try download the latest version see if it solve your issue: Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by lucamors1** [comment]
the problem is that i cannot ignore it.. or i don't know how to ignore it

**Comment by derekhe** [comment]
hmm, seems weird, sorry I can't figure out why.

**Comment by lucamors1** [comment]
you use a cracked MSFS version?

**Comment by lordmonish** [comment]
I do have the same problem and i use the cracked version of msfs

**Comment by derekhe** [comment]
> you use a cracked MSFS version?

? Are you use cracked version?
If so, stop using it, it is not supported.
