### ISSUE TITLE
[Feature] Run without IU 

### ISSUE THREAD

**Issue by CastorSmith89** [derekhe/msfs2020-google-map#59]
IU = UI

It would be great if you tool would run without UI then I can start a script to start all my Addon and mods as well as the MSFS client. Further, I could then run this tool on WSL instead windows.

**Comment by derekhe** [comment]
That's interesting and the far origin is without UI. Giving a UI is quite important for lots of people. 
I will mark this as a "nice to have" feature and will do it when I am free.

**Comment by CastorSmith89** [comment]
I agree. I will also check the code and may find solution to combine both as well and will let you know if it is running.

**Comment by derekhe** [comment]
Sure, if you can do please do PR
