### ISSUE TITLE
关于不使用代理的bug

### ISSUE THREAD

**Issue by MasonZhangZmx** [derekhe/msfs2020-google-map#6]
如果不使用代理或者使用全局代理的情况下，代码中原有本应该直接返回内容的链接会因为host的本地转发又会被程序捕获造成死循环，然后最终超时报错。
解决方案已经提交审核。

**Comment by derekhe** [comment]
并没有看到pull request呢？

**Comment by derekhe** [comment]
我已经做了一个修正，感谢！
