### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PJDunham** [derekhe/msfs2020-google-map#61]
**Describe the bug**
![MSFS_2020_google_map_install_issue](https://user-images.githubusercontent.com/94154902/141403301-c52f45df-1c6e-4800-b409-91bdf474cdb7.JPG)

here is a screen shot the the run bat box that pops up as requested...

**Comment by derekhe** [comment]
Duplicate issue: https://github.com/derekhe/msfs2020-google-map/issues/54

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5
