### ISSUE TITLE
[BUG] Still stuck at 'health check passed'

### ISSUE THREAD

**Issue by lordmonish** [derekhe/msfs2020-google-map#63]
when i open the mod it shows that the 'requirement is already satisfied' , and when i press RUN in mod it's just stuck at health check passed 

please help me out with this sir 
![image](https://user-images.githubusercontent.com/94129559/141428680-77be2271-2bc5-48c0-9d66-f06709cd974e.png)
![image](https://user-images.githubusercontent.com/94129559/141428727-b5b26718-6a65-4096-9675-e0206d0f3ab4.png)

and please inform me if your working on it sir

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by lordmonish** [comment]
no sir it just stops at health check passed even now :(

**Comment by lordmonish** [comment]
and also i use the latest version of msfs2020 but its cracked , but I don't think that being a cracked version is the problem 
because I myself use the unreal weather mod for this cracked version and it works without any problems, so i dont think there's much difference between these two mods cause they get their data from google , so please find a solution for this and you can tell me if iam wrong Sir

**Comment by derekhe** [comment]
Please have a look the video: https://youtu.be/Lk7GK5XLTt8
Or search "msfs 2020 google maps" in youtube to find out installation and usage tips.

**Comment by lordmonish** [comment]
![image](https://user-images.githubusercontent.com/94129559/141606725-1c2e03ff-b592-4b91-acb9-00acc57a236e.png

There's no change even after today's update sir

**Comment by derekhe** [comment]
The mod is working. You can try click "Run" button after you enter MFSF2020's main menu.

**Comment by derekhe** [comment]
First, click "Stop" and close the mod,
start MSFS2020 as normal
when in main menu
click "Run"
then see if it works.

**Comment by lordmonish** [comment]
okay i'll try and let you know sir

**Comment by lordmonish** [comment]
![image](https://user-images.githubusercontent.com/94129559/141625228-b92207e0-92e5-4097-941f-3f278be222b1.png)

did what what you told but there's no improvement sir

**Comment by derekhe** [comment]
The cracked version is quite old version which is not supported. Please keep using latest MS store version.

**Comment by lordmonish** [comment]
sir may i know for which veraion is this mod compatible cause i have the 1.19.9.0 version

**Comment by derekhe** [comment]
I don't know because cracked version may redirect the traffic to some other servers. Please don't use crack version.
I will close this now.
