### ISSUE TITLE
[BUG] Can't get the program to run: "Exception: Address and Name(s) must be specified."

### ISSUE THREAD

**Issue by localloobii** [derekhe/msfs2020-google-map#64]
**Describe the bug**
"Exception: Address and Name(s) must be specified."

I watched the introduction video and set it up exactly as I should, if I am not mistaken.
When I want to Run the program nothing happens and the console looks like this

It doesn't open the two firewall warnings like in the introduction/Installation video.
I tried it with Anti Virus and Firewall disabled. Both look the same (as in Screenshot)

**To Reproduce**
1. Go to run.bat and open as administrator
2. Click on "Test" --> "Connection is good"
3. Click on "Run"
4. See Screenshot

**Expected behavior**
To Run it like in the Video

**Screenshots**

![Screenshot (7)](https://user-images.githubusercontent.com/94167604/141440858-94cbd9b8-0cb1-4695-b430-c54d7db8e169.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H1 Build: 19043.1348
 - MOD Version newest from 11.11.2021
 - MSFS Version, MS Store: Newst

**Additional context**
--

**Comment by derekhe** [comment]
Please update this file C:\Windows\System32\drivers\etc\hosts
You can try remove this file. Please backup it.

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by derekhe** [comment]
@localloobii does it good now?

**Comment by localloobii** [comment]
I tried the new releas (from the 12th of November) and it was the Same issue (but I didnt update any driver)
![21-11](https://user-images.githubusercontent.com/94167604/141838901-cbe56be6-8348-4e7c-b9be-80c673655257.png)


Can you tell me how to do that? I mean I removed those files called host but what now? 
Greetings Max

Thanks for the effort though!

**Comment by derekhe** [comment]
How about this version? https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.7

**Comment by localloobii** [comment]
@derekh
![2021-11-16 16_47_01-Window](https://user-images.githubusercontent.com/94167604/142018393-f8d56c75-9423-4fe7-90e1-5a97f22f5fcb.png)
e

**Comment by derekhe** [comment]
thx, will have a look tmr



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 16, 2021 23:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [derekhe/msfs2020-google-map] [BUG] Can't get the program to run: "Exception: Address and Name(s) must be specified." (Issue #64)




 
![Uploading 2021-11-16 16_58_35-Window.png…](
 
 )
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by derekhe** [comment]
@localloobii Please try latest version, should fix that.

**Comment by localloobii** [comment]
@derekhe It runs!! Good Job! Thank you for the work and assistance
