### ISSUE TITLE
Version 20211111 Not working...

### ISSUE THREAD

**Issue by MikeEcho0815** [derekhe/msfs2020-google-map#65]
I am using Win11.

Error log of nginx:
 `2021/11/12 10:10:23 [notice] 28996#28640: using the "select" event method

2021/11/12 10:10:23 [notice] 28996#28640: using the "select" event method
2021/11/12 10:10:23 [notice] 28996#28640: nginx/1.21.3
2021/11/12 10:10:23 [notice] 28996#28640: nginx/1.21.3
2021/11/12 10:10:23 [info] 28996#28640: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 10:10:23 [notice] 28996#28640: start worker processes
2021/11/12 10:10:23 [notice] 28996#28640: start worker processes
2021/11/12 10:10:23 [notice] 28996#28640: start worker process 12860
2021/11/12 10:10:23 [notice] 28996#28640: start worker process 12860
2021/11/12 10:10:23 [notice] 12860#20632: nginx/1.21.3
2021/11/12 10:10:23 [notice] 12860#20632: nginx/1.21.3
2021/11/12 10:10:23 [info] 12860#20632: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 10:10:23 [notice] 12860#20632: create thread 22976
2021/11/12 10:10:23 [notice] 12860#20632: create thread 22976
2021/11/12 10:10:23 [notice] 12860#20632: create thread 24928
2021/11/12 10:10:23 [notice] 12860#20632: create thread 24928
2021/11/12 10:10:23 [notice] 12860#20632: create thread 25332
2021/11/12 10:10:23 [notice] 12860#20632: create thread 25332
2021/11/12 10:10:35 [error] 12860#22976: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:10:35 [error] 12860#22976: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:10:35 [error] 12860#22976: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:10:35 [warn] 12860#22976: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:10:35 [warn] 12860#22976: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:10:35 [info] 12860#22976: *1 client 127.0.0.1 closed keepalive connection`

**Comment by derekhe** [comment]
Fixing this

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.2.5

**Comment by MikeEcho0815** [comment]
Hey there!


Still getting this error:


2021/11/12 10:36:14 [notice] 5780#27580: using the "select" event method
2021/11/12 10:36:14 [notice] 5780#27580: using the "select" event method
2021/11/12 10:36:14 [notice] 5780#27580: nginx/1.21.3
2021/11/12 10:36:14 [notice] 5780#27580: nginx/1.21.3
2021/11/12 10:36:14 [info] 5780#27580: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 10:36:14 [notice] 5780#27580: start worker processes
2021/11/12 10:36:14 [notice] 5780#27580: start worker processes
2021/11/12 10:36:14 [notice] 5780#27580: start worker process 31492
2021/11/12 10:36:14 [notice] 5780#27580: start worker process 31492
2021/11/12 10:36:14 [notice] 31492#18944: nginx/1.21.3
2021/11/12 10:36:14 [notice] 31492#18944: nginx/1.21.3
2021/11/12 10:36:14 [info] 31492#18944: OS: 260200 build:9200, "", suite:100, type:1
2021/11/12 10:36:14 [notice] 31492#18944: create thread 15520
2021/11/12 10:36:14 [notice] 31492#18944: create thread 15520
2021/11/12 10:36:14 [notice] 31492#18944: create thread 8776
2021/11/12 10:36:14 [notice] 31492#18944: create thread 8776
2021/11/12 10:36:14 [notice] 31492#18944: create thread 18180
2021/11/12 10:36:14 [notice] 31492#18944: create thread 18180
2021/11/12 10:36:26 [error] 31492#15520: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:36:26 [error] 31492#15520: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:36:26 [error] 31492#15520: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:36:26 [warn] 31492#15520: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:36:26 [warn] 31492#15520: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /health HTTP/1.1", upstream: "http://[::1]:8000/health", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/11/12 10:36:26 [info] 31492#15520: *1 client 127.0.0.1 closed keepalive connection
2021/11/12 10:36:26 [info] 31492#15520: *4 client 127.0.0.1 closed keepalive connection

**Comment by derekhe** [comment]
I think the server is running. Do not care about these errors.

**Comment by MikeEcho0815** [comment]
Sadly the dont.

![image](https://user-images.githubusercontent.com/45940028/141451019-ea5edb79-d7cf-4556-b0fc-f85761fe9372.png)

**Comment by derekhe** [comment]
Did you turn on the online data feature in game? Please check the config, which mentioned in the https://youtu.be/Lk7GK5XLTt8?t=168

**Comment by MikeEcho0815** [comment]
MY bad... I am so embarresed.

It's working now. Thank you so much!

**Comment by derekhe** [comment]
Cool, enjoy :)

**Comment by lordmonish** [comment]
> MY bad... I am so embarresed.
> 
> It's working now. Thank you so much!

Sir do you use the cracked version ?, if yes please help me ...........
