### ISSUE TITLE
Google in World Map but not during fly

### ISSUE THREAD

**Issue by didierma34** [derekhe/msfs2020-google-map#67]
Hello,

I write here to explain something  to have information :)

Your software seems to be very good but I've a little problem.
I can see Google tiles in the World Map of MSFS when I choose an airport, that's sure :) :)
When I go to fly, I see the Bing Tiles, not Google. I'm sure because there is a new road in reality that I can't see during fly and I can see it in World Map befor flying (Google).
In MSFS, I've not any cash in config and all is all right.

Do you think there is a cash in MSFS to continue flying offline ?
Do you know if it's possible to erase this cache ?

Have you any idea ? :) :) :)

Thank's

**Comment by derekhe** [comment]
Please check the MSFS2020 config, which mentioned in the https://youtu.be/Lk7GK5XLTt8?t=168

**Comment by didierma34** [comment]
Thank's... I've already seen this vidéo.
It's my config...
So I don't know what can I do... :( 

I try to fly offline, and the tiles are the same than Bing... So.... :(
