### ISSUE TITLE
Value Error: embedded null  character[BUG] CHANGE TITLE

### ISSUE THREAD

**Issue by skipph** [derekhe/msfs2020-google-map#68]
**Describe the bug**
I get this error after hitting start on the ui.
**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
Please see duplicated issue: https://github.com/derekhe/msfs2020-google-map/issues/54

**Comment by skipph** [comment]
Thanks for the links. Got it resolved. There was no entries in my hosts file. But I deleted anyway and restarted the program which now works.
