### ISSUE TITLE
[BUG] error message

### ISSUE THREAD

**Issue by Ostermundiger** [derekhe/msfs2020-google-map#69]
why i get this error message?

Generate nginx file failed

MS store Version
Mod version 2.2.5

**Comment by derekhe** [comment]
Please give a screen shot of error, thanks

**Comment by derekhe** [comment]
@Ostermundiger Please give a screen shot of error, thanks

**Comment by Ostermundiger** [comment]
hi

here is the screensjot, hope this helps you

greetings

Am So., 14. Nov. 2021 um 02:32 Uhr schrieb hesicong <
***@***.***>:

**Comment by derekhe** [comment]
Sorry man, I can’t see your screenshots.

**Comment by Ostermundiger** [comment]
strange ..  the pic (PNG) is attached


hesicong ***@***.***> schrieb am Mi., 17. Nov. 2021, 02:47:

**Comment by derekhe** [comment]
Seems you are sending from email, no image is showing in GitHub pages.

**Comment by Ostermundiger** [comment]
![Screenshot (104)](https://user-images.githubusercontent.com/94188955/142118747-e06d7ff6-1c02-4e38-9f1b-73f70575ea28.png)

**Comment by derekhe** [comment]
Seems it is an old version now, can you try latest version?

**Comment by Ostermundiger** [comment]
hi again

good news, it works with 2.2.8 !!!

thank you and keep it updated

hesicong ***@***.***> schrieb am Mi., 17. Nov. 2021, 03:42:
