### ISSUE TITLE
[BUG] SSL Error

### ISSUE THREAD

**Issue by Sim-Dude** [derekhe/msfs2020-google-map#71]
**Describe the bug**
Google no longer works on my computer. No issues yesterday. Today it brings up a SSL error and I click "Yes" to accept it. It locks up at that time and I have to End Process on MSFS2020. Yesterday I got the same SSL error, clicked "Yes" and it worked fine. Anything I need to do to correct my problem? Thanks for the great app.

**To Reproduce**
Start the run.bat "As Administrator"
Start MSFS2020

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MOD Version [Most recent downloaded from flightsim.to]
 - MSFS Version, MS Store

**Additional context**
It gave me the error yesterday and selecting Yes allowed the program to run.

**Comment by derekhe** [comment]
If you can run it fine, just accept the SSL error.
