### ISSUE TITLE
Google Maps Mod crashes MSFS2020 and restarts computer

### ISSUE THREAD

**Issue by franmolders** [derekhe/msfs2020-google-map#72]
On MSFS 2020 Standard edition, your mod freezes the simulation and restarts the computer after a while on the simulation. This does not happen with Bing maps (Google Maps mod non active).

**Comment by derekhe** [comment]
I have no idea about this.
How's going now?

**Comment by franmolders** [comment]
Hello again. I increased virtual memory in my system, and reboots are not
so frequent now, but they keep happening. Going back to bing maps to check
for further crash rate of incidence.

**Comment by derekhe** [comment]
How much memory do you have?

**Comment by franmolders** [comment]
16 Bg physical RAM memory. 8 Gb in my video card. Just increased virtual memory to 25 Gb.

**Comment by derekhe** [comment]
16GB for MSFS2020 is not quite enough especially run high details. Yes increase the VM may help.
