### ISSUE TITLE
ERROR: You are using Port 443, please close them

### ISSUE THREAD

**Issue by rwilsonlj** [derekhe/msfs2020-google-map#74]
**Describe the bug**
Upon execution of RUN.BAT, it opens a DOS window and the "RUN" window and immediately get this error message and after clicking OK, app stops_

**To Reproduce**
Every time I run it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream Current Version of MSFS 2020 store

**Additional context**
Add any other context about the problem here. Run fine yesterday, don't know what is different. Any help appreciated.

**Comment by derekhe** [comment]
Please have a look to find out: https://www.youtube.com/watch?v=GMcptMj4jx8
