### ISSUE TITLE
Also stuck at "Health Check passed"

### ISSUE THREAD

**Issue by KelvinNZ** [derekhe/msfs2020-google-map#75]
Windows 11 installed
checked my firewall is configured correctly and app is allowed
I do not need proxy for Google maps
Run as admin 
Certificate is installed correctly
run your app before starting MSFS - did not work
Run MSFS to main menu then started your app but do not show google maps

Is there something else I can try?

Verbose output:

Exact match:
Element 2:
Serial Number: c9dfffaa7d7e8ef1c6bc38e6781f0fb1
Issuer: CN=mkcert DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, OU=DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, O=mkcert development CA
 NotBefore: 19/08/2021 3:01 am
 NotAfter: 19/11/2023 3:01 am
Subject: OU=DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, O=mkcert development certificate
Non-root Certificate
Cert Hash(sha1): ae4cfdbea30eaa635443b6914b3b863b52f693de

Certificate "DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF" already in store.
CertUtil: -addstore command completed successfully.
{'kh.ssl.ak.tiles.virtualearth.net': '23.45.81.145', 'khstorelive.azureedge.net': '104.212.68.106'}
Overriding hosts
 * Serving Flask app 'server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.50.200:8000/ (Press CTRL+C to quit)
Checking mock server health
127.0.0.1 - - [13/Nov/2021 22:53:46] "GET /health HTTP/1.0" 200 -
Mock server health passed
Checking nginx server health
Health check passed

**Comment by anthony1956** [comment]
GOT SAME PROB HEALTH OK BUT NO MAPS DOWNLOADING

**Comment by derekhe** [comment]
Please check these videos see if something doing wrong:
https://youtu.be/Lk7GK5XLTt8
https://www.youtube.com/watch?v=E11XsrBdzcg
https://www.youtube.com/results?search_query=msfs+2020+google+maps

**Comment by KelvinNZ** [comment]
Thanks for responding to me and I do appreciate your effort. 

However I have done everything you have asked so this seems to be a conflict with something in windows but I am unable to fix that because I don't know how the program works. 

Can I suggest better verbose logging?

**Comment by KelvinNZ** [comment]
I have a super speedy internet connection and I have reinstalled MSFS without any mods or anything other than default install and the same problem is happening.

So, this is an external issue which may be even external to the app but there's nothing else I can see is causing the app to be stuck at Health Check passed. I will appreciate any help.

**Comment by derekhe** [comment]
that's strange, I added the log for testing the server so on your computer it should goes to google view.
Can you see the google earth images when you in main menu?
If you can capture a screen video and let me have a look, that would be best.

**Comment by oliveiralberto** [comment]
I am having this issue to. before the last update the program work very good. but now i am stuck at health check passed.. and the sim does load anymore.

**Comment by derekhe** [comment]
@oliveiralberto  @KelvinNZ   I need more details, if you guys can provide screen recording, that would help me to trouble shooting it. Thanks

**Comment by KelvinNZ** [comment]
It seems your app does not hook into MSFS I am using steam by the way.

I have no Google maps in the world map. Only shows default textures. Bing is not enabled and photogrammetry is greyed out.

You ask me to show you screenshots but of what? I am doing nothing extra, I download your app and run it but get the health check message then it stops and does not progress.

If I had source code I could run in visual studio and help debug it.

I know you can't see what I'm doing but trust me, I have done everything in the YouTube video and instructions.

Something is the same with others who have the issue but seeing the code no doubt will give a better understanding. I'm out of options.
________________________________

**Comment by KelvinNZ** [comment]
I will try to get a video but I don't have alot of time to make it.
________________________________

**Comment by derekhe** [comment]
Bing is not enabled and photogrammetry is greyed out.

Please keep these Enable, sometimes it turn off.

**Comment by KelvinNZ** [comment]
But there's nothing in your instructions to explain this. I will try that and let you know.
________________________________

**Comment by derekhe** [comment]
Thanks, its in the video https://youtu.be/Lk7GK5XLTt8?t=164

**Comment by KelvinNZ** [comment]
Yes but it doesn't explain that the settings can change like you said it sometimes could. I set everything like the video shows.

I also see your CMD window shows the activity but when I run the app it stops at that Health Check Passed part. Then nothing else so this part is still a problem.
________________________________

**Comment by KelvinNZ** [comment]
ok, I am utterly confused. I fired up my sim this morning to check the "Data" settings for Bing and photogrammetry but without changing anything your app is now working. The frustrating part is that I have done absolutely nothing since the issue started. Typical experience in I.T where issues are self-healing *shrug*.

I wish I had some info as to what fixed this but I don't, it literally just started working without any interaction from me. 

...
Thanks for trying to help me Derek, I know this is not payware and your support is voluntary so I do need to acknowledge that.

**Comment by anthony1956** [comment]
No images since new version 6 installed

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by anthony1956** [comment]
You did well but new updates stopped it load health check ok ect but then nothing

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2

**Comment by relbaek** [comment]
Still having same problem even with this new version

**Comment by KelvinNZ** [comment]
Mine is working as I said already but I don't know what resolved the issue, I wish I did because it may help others. I did nothing extra, that I can recall except run the program me when inside the world map rather than before running the sim.
________________________________

**Comment by derekhe** [comment]
ok, will close this.
