### ISSUE TITLE
[BUG] Get Error 13 / permission denied

### ISSUE THREAD

**Issue by Juergen1967** [derekhe/msfs2020-google-map#76]
Hi,
after I start the .bat as admin, I get the following window:

![image](https://user-images.githubusercontent.com/58910885/141615172-643ed0e7-275f-4f90-a81a-9b3dc78dfa7b.png)

Notice: After the traceback, there is obviously a problem with the permissions.  I thought that all permissions should work fine because I started the Batch as Admin.

Any help would be much appreciated!

Thanks for the good work!

All the best

J.

**Comment by derekhe** [comment]
Similar issue: https://github.com/derekhe/msfs2020-google-map/issues/54
