### ISSUE TITLE
[BUG] PHOTOGRAMETRY LOST

### ISSUE THREAD

**Issue by KDABLACK** [derekhe/msfs2020-google-map#80]
YESTERDAY IT WORKS FINE  
TODAY I VE INSTALLED THE LAST VERSION AND NOW PHOTOGRAMETRY DISAPPEAR IN MSFS

NGINX DONT START TOO
![nginx](https://user-images.githubusercontent.com/70862419/141647804-d64aa215-474b-4574-8d70-f38cd3d4d4db.jpg)

GOOD WORK

**Comment by derekhe** [comment]
Please have a look at MSFS2020 data configuration

**Comment by KDABLACK** [comment]
i ve re lauch the computer and have again a message about nginx i have close the app re launch and load msfs and everythings good now itself

thanks

**Comment by derekhe** [comment]
cool, will close this now.
