### ISSUE TITLE
[BUG] Noticeable texture edges

### ISSUE THREAD

**Issue by Crispy136** [derekhe/msfs2020-google-map#82]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
Noticeable texture edges.

**To Reproduce**
Fly around YBUD to the southwest or north.

**Screenshots**
![2021-11-13](https://user-images.githubusercontent.com/71639706/141660883-0c8f3494-e1db-4bbb-8f52-6bc9cce61aa0.png)

**Desktop (please complete the following information):**
 - OS: WIn11
 - MOD Version 2.2.6
 - MSFS Version, Stream

**Additional context**
The textures also change slightly as you approach although the edge remains.  The screen shot shows just a single instance but there were often multiple instances at the same time.  Running with MSFS rolling cache disabled.

**Comment by derekhe** [comment]
Yes, I know this issue because the mod adjust the photogrammetry image's brightness, which may cause this issue. I will try to fix this in future release.

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.0
