### ISSUE TITLE
MSFS freezing on the LOADING screen when the app is running in the background.

### ISSUE THREAD

**Issue by rexetorize** [derekhe/msfs2020-google-map#84]
Every time I run msfs with msfs2020-google-map running in the background, it is getting stuck in the loading screen.  I tried running msfs in the safe mode and it's still getting stuck in the loading screen. I tried running msfs2020-google-map and msfs with firewall and windows defender off but still getting stuck. Also, google maps is not blocked in my region, so that's not an issue either. please help me fix this as I really wanna try out this mod.

*Desktop (please complete the following information)
 - Windows 10, version 21H1
 - GTX 1060 6GB
 - RYZEN 5 2600X
 - 16GB MEMORY
 - MOD Version - (2.2.6)
 - MSFS Version - UPDATED TO LATEST UPDATE 
 - BOUGHT FROM STEAM

**Comment by derekhe** [comment]
Please have a look at https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Comment by rexetorize** [comment]
yes, well you just have to run msfs and then launch it and it just works fine. Thanks for the help. :)
