### ISSUE TITLE
[BUG] CHANGE TITLE

### ISSUE THREAD

**Issue by Juergen1967** [derekhe/msfs2020-google-map#85]
Hi. 
I had the same problem as in issue #54 . I deleted the file and ran the batch file as Administrator.
I put an exception into my Kaspersky.

But now I get the following error:

![image](https://user-images.githubusercontent.com/58910885/141672808-ca6a5bcb-f148-4d68-9e8c-5180ad23cc41.png)

Obviously, there is a file missing "___init___.py" missing.
Error is "No module named "python_hosts.hosts"

Any idea?

thx
J.

**Comment by derekhe** [comment]
Did you get this unzipped correctly? Seems some files is lost.

**Comment by Juergen1967** [comment]
Hey,
thanks for the reply.

Here is the content I unzipped

![image](https://user-images.githubusercontent.com/58910885/141677503-41d57913-dc5c-4d0b-9b66-940dcabdb498.png)

Do you see anything missing?

Thanks !
J.

**Comment by Juergen1967** [comment]
The missing file is in a different Subfolder:

![image](https://user-images.githubusercontent.com/58910885/141677654-2e6258d7-2845-44e5-9852-107e4f88a761.png)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-google-map/releases/download/2.2.6/msfs2020-google-map-2021-11-13.zip

Could you try download this and unzip to D:\msfs2020\

**Comment by Juergen1967** [comment]
By D:\msfs2020 you mean the game directory?

**Comment by derekhe** [comment]
I mean one folder without space inside.

**Comment by Juergen1967** [comment]
Same problem when running from G:\MSFSGOOGLE


![image](https://user-images.githubusercontent.com/58910885/141685050-c53f9b39-b554-42b9-96bb-e99006575ddc.png)

**Comment by derekhe** [comment]
Hmm, ok, please stay tunned for latest version. I'm fixing this module.

**Comment by Juergen1967** [comment]
Sounds great! Thanks for your work, mate.

**Comment by derekhe** [comment]
@Juergen1967 could you try latest version? https://github.com/derekhe/msfs2020-google-map/releases/download/2.2.7/msfs2020-google-map-2021-11-14.zip

**Comment by Juergen1967** [comment]
Hey. 
I tried out the new version. Now I get this error

![image](https://user-images.githubusercontent.com/58910885/141839289-19110545-dd92-4ed3-8b46-374b5add15b3.png)

**Comment by derekhe** [comment]
The hosts file are readonly, please change the permission so that my software can modify it:
https://superuser.com/questions/958991/windows-10-cant-edit-hosts-file

**Comment by derekhe** [comment]
@Juergen1967  work now?
