### ISSUE TITLE
Nginx.exe process not found

### ISSUE THREAD

**Issue by WebMaximus** [derekhe/msfs2020-google-map#86]
When I run the batch file, I see an error message saying Nginx.exe process wasn't found or something along those lines (not in front of my PC right now).

Have only made a quick test of the mod so far and as far as I could tell, it seemed to work. Was just curious why I see this error message and if that indicates a problem I haven't discovered yet?

**Comment by derekhe** [comment]
This is known issue and I removed it just now.
I will update the version soon.

**Comment by WebMaximus** [comment]
Awesome, many thanks! Both for the mod itself as well as for being so responsive.

Looking forward to spend some more time with the mod and do expect a donation coming your way in the near future.
