### ISSUE TITLE
[BUG] Works for about 10 mins but then it stops

### ISSUE THREAD

**Issue by ziher123** [derekhe/msfs2020-google-map#87]
**Describe the bug**
Works fine for 10 mins but then stops loading textures. After that my connection to internet basically doesn't work anymore (interestingly crypto mining still works).
It takes about half an hour for web pages to start loading again, even on different machines running different versions of windows.
Am i being blocked by Google or my ISP here?

**To Reproduce**
Happens all the time no matter what.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MOD Version  2.2.6
 - MSFS Steam Version

**Additional context**

**Comment by derekhe** [comment]
hmm, that's interesting I have no idea right now

**Comment by ziher123** [comment]
Ok, so i disabled IPv6 and now it works like a charm:)
