### ISSUE TITLE
[BUG] Tiles pop in and out, and range is very low

### ISSUE THREAD

**Issue by Inexorable95** [derekhe/msfs2020-google-map#89]
**Describe the bug**
When using the mod (latest version, latest version of MFS), with no other mods, with a 1gbps internet connection and a powerful computer, the tiles pop in and out when in move.
Even if I remain static and just move the camera, the tiles will pop in and out (some tiles that I have previously downloaded will disappear)

**To Reproduce**
My ingame LOD is set to 200
**Screenshots**
![Capture5](https://user-images.githubusercontent.com/76154362/141759081-2cd0c114-c56b-4aa2-a194-21ac7be70b5c.PNG)

**Desktop (please complete the following information):**
 - OS: W10
 - MOD Version 2.2.7
 - MSFS Version, MS Store or Stream : MS store

**Additional context**
The console shows no error, it downloads the tiles properly and fast

**Comment by derekhe** [comment]
It may be caused by the "Rolling Cache" enabled in MSFS data configuration. Please delete the rolling data.

**Comment by Inexorable95** [comment]
> It may be caused by the "Rolling Cache" enabled in MSFS data configuration. Please delete the rolling data.

I tried this, but it doesn't fix the issue

**Comment by derekhe** [comment]
Could you try to record a screen capture video and share to me (maybe youtube)

**Comment by Inexorable95** [comment]
After disabling MFS cache, clearing it, AND uninstalling your program and reinstalling it, the problem is gone ! Thanks
