### ISSUE TITLE
Trees dissapearing

### ISSUE THREAD

**Issue by velorond** [derekhe/msfs2020-google-map#90]
Whan i use this mod, trees dissapear.
I tried to disable it and the trees where back again.

Windows 10
mod ver 2.2.7

<a href="https://ibb.co/BgbndLt"><img src="https://i.ibb.co/BgbndLt/Namnl-s.jpg" alt="Namnl-s" border="0"></a> <a href="https://ibb.co/9ycJ4dn"><img src="https://i.ibb.co/9ycJ4dn/Namnl-s2.jpg" alt="Namnl-s2" border="0"></a>

**Comment by derekhe** [comment]
Trees seems rendered as autogen objects which means MSFS2020 will recognize that area has trees and plant trees there.
For google images, I see the image is not so clear (seems blue), so it may not show as trees. 
You can try different place.
