### ISSUE TITLE
[BUG] Nginx still running

### ISSUE THREAD

**Issue by whoot** [derekhe/msfs2020-google-map#93]
**Describe the bug**
Two instances of NGINX are running after closing the program.

**To Reproduce**

1. Execute 'run.bat' as administrator
2. Use it together with MSFS
3. Close the app
4. Open Task Manager and see that nginx (32 bit) is still running

Opening the app again will result in an error claiming that port 443 is used by a program.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MOD Version 2.2.8 (2021-11-16)
 - MSFS Steam

**Comment by derekhe** [comment]
I mentioned in the app that you must click "Stop" before you exit the program.

**Comment by whoot** [comment]
Oh yeah, seems like I missed that. Sorry!
