### ISSUE TITLE
[BUG] No maps are loaded, when mod is inactive MSFS breaks connection to Bing maps frequently

### ISSUE THREAD

**Issue by Andreas-Germany** [derekhe/msfs2020-google-map#94]
Hi,

when I try to use the version msfs2020-google-map-2021-11-14.zip with my
bought DVD-version FS 2020 (Ver. 1.20.6.0) no GoogleMaps are load and the 
FS hangs. The rolling cache is set to OFF.
When I have stopped your mod and try to start the FS with the original
Bing-maps again, I get online connection breaks frequently. I never had
this problem before. It seems that your mod has changed something in the
flightsimulator configuration.
How can I solve this problem? I never had connection breaks before I
tried to install your mod. Please assist me... 

Thanks in advance
Andreas from Germany

**Comment by derekhe** [comment]
Please checkout: https://github.com/derekhe/msfs2020-google-map/wiki/Welcome

**Comment by Andreas-Germany** [comment]
Hello,
I found the solution to get everything up and running (with and without the mod). Thanks to derekhe !!

Here is what to be done
================


My configuration:

Windows 10 Pro Vers. 21H1
MSFS 2020  Vers. 1.21.13.0
Mod Vers.  msfs2020-google-map-2021-11-16.zip

FIRST run the MSFS 2020

When its loaded, right click on run.bat of the mod and run it as administrator.
In the now opened mod-window click RUN.
Enjoy the game with Google maps....
BEFORE close the mod-window click STOP to reset the hosts

If you want to use the MSFS 2020 with the original Bing maps, simply run the MSFS
without starting the mod. This only works if you have STOPed the mod before,
otherwise no maps can be loaded.

The mod will change your hosts file (C:\windows\system32\drivers\etc\hosts) to place these entries inside:

127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

So that the traffic to these servers will redirect to the mod to give you google map. If you have trouble after exit the mod (don't forget to use the STOP button), please check this file and delete these two lines (You need full file access to be able to do that).

See also the website:
https://github.com/derekhe/msfs2020-google-map/wiki/Welcome

**Comment by derekhe** [comment]
Yes, please read the docs first
