### ISSUE TITLE
[Feature] CMD command to start your tool + start streaming + start MSFS

### ISSUE THREAD

**Issue by Olfdev** [derekhe/msfs2020-google-map#97]
Hello,
First of all, great job on this tool, it works absolutely flawlessly!

I was wondering if there was any way to create a batch file that would automatically:
- start your tool
- start streaming
- start MSFS

This way I could only use one BAT shortcut instead of manually start the tool, then click Start streaming, then start MSFS.

Thank you and keep up the good work!

**Comment by derekhe** [comment]
That's possible in someway but consider different system with different version (ms store or steam version, it is hard to do it correctly). Sorry I won't create this feature consider this.

**Comment by Olfdev** [comment]
But could I do it myself via some commandline? :)

**Comment by derekhe** [comment]
Sorry, currently not cmd line is there and won't implement in future.

**Comment by Olfdev** [comment]
OK, thanks for the quick answers! I'll just use a macro then.
