### ISSUE TITLE
Missing Packets 

### ISSUE THREAD

**Issue by Jumtri** [derekhe/msfs2020-google-map#99]
Last Message on the Command window is "Health check passed"
Then after FS is Launched i've got the message “You are missing packages that are essential to run Microsoft Flight Simulator. Please update the application and try again.”

Same message without the google app launched so I can't use FS anymore :(

Thanks for help

**Comment by derekhe** [comment]
Can u give me a screenshots?

**Comment by Jumtri** [comment]
Hello

Here is a photo
I did a clean install of FS with no folder in community and  it worked

But when i add the addons in community folder i’ve got the same message, it’s in conflict with some addon.

The problem is i can’t go back with empty community folder it doesn’t work i need to install FS again

Do you have an idea ?
Thanks
Florent

**Comment by derekhe** [comment]
Did you read the page? https://github.com/derekhe/msfs2020-google-map/wiki/Welcome

**Comment by derekhe** [comment]
@Jumtri fixed?

**Comment by Jumtri** [comment]
Hello 

Yes it’s fixed in fact it was due to the update SU7 installed at same time
Thanks for support and for this amazing mod
Regards
Florent
